/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pokemonstadium.glb --types 
*/
import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.SkinnedMesh;
    mesh_1: THREE.SkinnedMesh;
    mesh_2: THREE.SkinnedMesh;
    mesh_3: THREE.SkinnedMesh;
    mesh_4: THREE.SkinnedMesh;
    mesh_5: THREE.SkinnedMesh;
    mesh_6: THREE.SkinnedMesh;
    mesh_7: THREE.SkinnedMesh;
    mesh_8: THREE.SkinnedMesh;
    mesh_9: THREE.SkinnedMesh;
    mesh_10: THREE.SkinnedMesh;
    mesh_11: THREE.SkinnedMesh;
    mesh_12: THREE.SkinnedMesh;
    mesh_13: THREE.SkinnedMesh;
    mesh_14: THREE.SkinnedMesh;
    mesh_15: THREE.SkinnedMesh;
    mesh_16: THREE.SkinnedMesh;
    mesh_17: THREE.SkinnedMesh;
    mesh_18: THREE.SkinnedMesh;
    mesh_19: THREE.SkinnedMesh;
    mesh_20: THREE.SkinnedMesh;
    mesh_21: THREE.SkinnedMesh;
    mesh_22: THREE.SkinnedMesh;
    mesh_23: THREE.SkinnedMesh;
    mesh_24: THREE.SkinnedMesh;
    mesh_25: THREE.SkinnedMesh;
    mesh_26: THREE.SkinnedMesh;
    mesh_27: THREE.SkinnedMesh;
    mesh_28: THREE.SkinnedMesh;
    mesh_29: THREE.SkinnedMesh;
    mesh_30: THREE.SkinnedMesh;
    JOBJ_0: THREE.Bone;
  };
  materials: {
    ["Joint_1_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_10_Material_10.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_13_Material_13.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_17_Material_17.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_18_Material_18.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_1_Material_1.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_20_Material_20.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_21_Material_21.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_23_Material_23.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_24_Material_24.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_25_Material_25.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_26_Material_26.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_5_Material_5.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_7_Material_7.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_8_Material_8.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_10_Material_10.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_11_Material_11.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_13_Material_13.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_14_Material_14.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_15_Material_15.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_16_Material_16.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_17_Material_17.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_18_Material_18.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_19_Material_19.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_1_Material_1.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_20_Material_20.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_23_Material_23.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_28_Material_28.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_29_Material_29.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_26_Material_26.001"]: THREE.MeshBasicMaterial;
  };
  animations: GLTFAction[];
};
interface GLTFAction extends THREE.AnimationClip {
  name: never;
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<
    JSX.IntrinsicElements["skinnedMesh"] | JSX.IntrinsicElements["bone"]
  >
>;

export function Pokemonstadium(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/pokemonstadium.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.JOBJ_0} />
      <skinnedMesh
        geometry={nodes.mesh_0.geometry}
        material={materials["Joint_1_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_0.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_1.geometry}
        material={materials["Joint_1_Object_10_Material_10.001"]}
        skeleton={nodes.mesh_1.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_2.geometry}
        material={materials["Joint_1_Object_13_Material_13.001"]}
        skeleton={nodes.mesh_2.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_3.geometry}
        material={materials["Joint_1_Object_17_Material_17.001"]}
        skeleton={nodes.mesh_3.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_4.geometry}
        material={materials["Joint_1_Object_18_Material_18.001"]}
        skeleton={nodes.mesh_4.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_5.geometry}
        material={materials["Joint_1_Object_1_Material_1.001"]}
        skeleton={nodes.mesh_5.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_6.geometry}
        material={materials["Joint_1_Object_20_Material_20.001"]}
        skeleton={nodes.mesh_6.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_7.geometry}
        material={materials["Joint_1_Object_21_Material_21.001"]}
        skeleton={nodes.mesh_7.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_8.geometry}
        material={materials["Joint_1_Object_23_Material_23.001"]}
        skeleton={nodes.mesh_8.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_9.geometry}
        material={materials["Joint_1_Object_24_Material_24.001"]}
        skeleton={nodes.mesh_9.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_10.geometry}
        material={materials["Joint_1_Object_25_Material_25.001"]}
        skeleton={nodes.mesh_10.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_11.geometry}
        material={materials["Joint_1_Object_26_Material_26.001"]}
        skeleton={nodes.mesh_11.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_12.geometry}
        material={materials["Joint_1_Object_5_Material_5.001"]}
        skeleton={nodes.mesh_12.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_13.geometry}
        material={materials["Joint_1_Object_7_Material_7.001"]}
        skeleton={nodes.mesh_13.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_14.geometry}
        material={materials["Joint_1_Object_8_Material_8.001"]}
        skeleton={nodes.mesh_14.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_15.geometry}
        material={materials["Joint_2_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_15.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_16.geometry}
        material={materials["Joint_2_Object_10_Material_10.001"]}
        skeleton={nodes.mesh_16.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_17.geometry}
        material={materials["Joint_2_Object_11_Material_11.001"]}
        skeleton={nodes.mesh_17.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_18.geometry}
        material={materials["Joint_2_Object_13_Material_13.001"]}
        skeleton={nodes.mesh_18.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_19.geometry}
        material={materials["Joint_2_Object_14_Material_14.001"]}
        skeleton={nodes.mesh_19.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_20.geometry}
        material={materials["Joint_2_Object_15_Material_15.001"]}
        skeleton={nodes.mesh_20.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_21.geometry}
        material={materials["Joint_2_Object_16_Material_16.001"]}
        skeleton={nodes.mesh_21.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_22.geometry}
        material={materials["Joint_2_Object_17_Material_17.001"]}
        skeleton={nodes.mesh_22.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_23.geometry}
        material={materials["Joint_2_Object_18_Material_18.001"]}
        skeleton={nodes.mesh_23.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_24.geometry}
        material={materials["Joint_2_Object_19_Material_19.001"]}
        skeleton={nodes.mesh_24.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_25.geometry}
        material={materials["Joint_2_Object_1_Material_1.001"]}
        skeleton={nodes.mesh_25.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_26.geometry}
        material={materials["Joint_2_Object_20_Material_20.001"]}
        skeleton={nodes.mesh_26.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_27.geometry}
        material={materials["Joint_2_Object_23_Material_23.001"]}
        skeleton={nodes.mesh_27.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_28.geometry}
        material={materials["Joint_2_Object_28_Material_28.001"]}
        skeleton={nodes.mesh_28.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_29.geometry}
        material={materials["Joint_2_Object_29_Material_29.001"]}
        skeleton={nodes.mesh_29.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
      <skinnedMesh
        geometry={nodes.mesh_30.geometry}
        material={materials["Joint_1_Object_26_Material_26.001"]}
        skeleton={nodes.mesh_30.skeleton}
        position={[-372, -270, -230.258]}
        scale={0.045}
      />
    </group>
  );
}

useGLTF.preload("/pokemonstadium.glb");
