/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 yoshisstory.glb --types 
*/
import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.SkinnedMesh;
    mesh_1: THREE.SkinnedMesh;
    mesh_2: THREE.SkinnedMesh;
    mesh_3: THREE.SkinnedMesh;
    mesh_4: THREE.SkinnedMesh;
    mesh_5: THREE.SkinnedMesh;
    mesh_6: THREE.SkinnedMesh;
    mesh_7: THREE.SkinnedMesh;
    mesh_8: THREE.SkinnedMesh;
    mesh_9: THREE.SkinnedMesh;
    mesh_10: THREE.SkinnedMesh;
    mesh_11: THREE.SkinnedMesh;
    mesh_12: THREE.SkinnedMesh;
    mesh_13: THREE.SkinnedMesh;
    mesh_14: THREE.SkinnedMesh;
    mesh_15: THREE.SkinnedMesh;
    mesh_16: THREE.SkinnedMesh;
    mesh_17: THREE.SkinnedMesh;
    mesh_18: THREE.SkinnedMesh;
    mesh_19: THREE.SkinnedMesh;
    mesh_20: THREE.SkinnedMesh;
    mesh_21: THREE.SkinnedMesh;
    mesh_22: THREE.SkinnedMesh;
    mesh_23: THREE.SkinnedMesh;
    mesh_24: THREE.SkinnedMesh;
    mesh_25: THREE.SkinnedMesh;
    mesh_26: THREE.SkinnedMesh;
    mesh_27: THREE.SkinnedMesh;
    JOBJ_0: THREE.Bone;
    Joint_1_Object_0_SINGLE: THREE.Bone;
    Joint_1_Object_1_SINGLE: THREE.Bone;
    Joint_2_Object_0_SINGLE: THREE.Bone;
    Joint_2_Object_1_SINGLE: THREE.Bone;
    Joint_3_Object_0_SINGLE: THREE.Bone;
    Joint_3_Object_1_SINGLE: THREE.Bone;
    Joint_3_Object_2_SINGLE: THREE.Bone;
    Joint_3_Object_3_SINGLE: THREE.Bone;
    Joint_3_Object_4_SINGLE: THREE.Bone;
    Joint_3_Object_5_SINGLE: THREE.Bone;
    Joint_3_Object_6_SINGLE: THREE.Bone;
    Joint_3_Object_7_SINGLE: THREE.Bone;
    Joint_3_Object_8_SINGLE: THREE.Bone;
    Joint_3_Object_9_SINGLE: THREE.Bone;
    Joint_3_Object_10_SINGLE: THREE.Bone;
    Joint_3_Object_11_SINGLE: THREE.Bone;
    Joint_3_Object_12_SINGLE: THREE.Bone;
    Joint_3_Object_13_SINGLE: THREE.Bone;
    Joint_3_Object_14_SINGLE: THREE.Bone;
    Joint_3_Object_15_SINGLE: THREE.Bone;
    Joint_3_Object_16_SINGLE: THREE.Bone;
    Joint_3_Object_17_SINGLE: THREE.Bone;
    Joint_3_Object_18_SINGLE: THREE.Bone;
    Joint_3_Object_19_SINGLE: THREE.Bone;
    Joint_3_Object_20_SINGLE: THREE.Bone;
    Joint_3_Object_21_SINGLE: THREE.Bone;
    Joint_3_Object_22_SINGLE: THREE.Bone;
    Joint_3_Object_23_SINGLE: THREE.Bone;
    Joint_3_Object_24_SINGLE: THREE.Bone;
    Joint_3_Object_25_SINGLE: THREE.Bone;
    Joint_4_Object_0_SINGLE: THREE.Bone;
    Joint_4_Object_1_SINGLE: THREE.Bone;
    Joint_4_Object_2_SINGLE: THREE.Bone;
    Joint_4_Object_3_SINGLE: THREE.Bone;
    Joint_4_Object_4_SINGLE: THREE.Bone;
    Joint_4_Object_5_SINGLE: THREE.Bone;
    Joint_4_Object_6_SINGLE: THREE.Bone;
    Joint_4_Object_7_SINGLE: THREE.Bone;
    Joint_4_Object_8_SINGLE: THREE.Bone;
    Joint_4_Object_9_SINGLE: THREE.Bone;
    Joint_4_Object_10_SINGLE: THREE.Bone;
    Joint_4_Object_11_SINGLE: THREE.Bone;
    Joint_4_Object_12_SINGLE: THREE.Bone;
    Joint_4_Object_13_SINGLE: THREE.Bone;
    Joint_4_Object_14_SINGLE: THREE.Bone;
    Joint_4_Object_15_SINGLE: THREE.Bone;
    Joint_4_Object_16_SINGLE: THREE.Bone;
    Joint_4_Object_17_SINGLE: THREE.Bone;
    Joint_4_Object_18_SINGLE: THREE.Bone;
    Joint_4_Object_19_SINGLE: THREE.Bone;
    Joint_6_Object_0_SINGLE: THREE.Bone;
    Joint_6_Object_1_SINGLE: THREE.Bone;
    Joint_7_Object_0_SINGLE: THREE.Bone;
    Joint_7_Object_1_SINGLE: THREE.Bone;
    Joint_12_Object_0_SINGLE: THREE.Bone;
    Joint_12_Object_1_SINGLE: THREE.Bone;
    Joint_13_Object_0_SINGLE: THREE.Bone;
    Joint_13_Object_1_SINGLE: THREE.Bone;
    Joint_14_Object_0_SINGLE: THREE.Bone;
    Joint_14_Object_1_SINGLE: THREE.Bone;
    Joint_15_Object_0_SINGLE: THREE.Bone;
    Joint_15_Object_1_SINGLE: THREE.Bone;
    Joint_16_Object_0_SINGLE: THREE.Bone;
    Joint_16_Object_1_SINGLE: THREE.Bone;
    Joint_16_Object_2_SINGLE: THREE.Bone;
    Joint_16_Object_3_SINGLE: THREE.Bone;
    Joint_16_Object_4_SINGLE: THREE.Bone;
    Joint_16_Object_5_SINGLE: THREE.Bone;
    Joint_16_Object_6_SINGLE: THREE.Bone;
    Joint_16_Object_7_SINGLE: THREE.Bone;
    Joint_16_Object_8_SINGLE: THREE.Bone;
    Joint_16_Object_9_SINGLE: THREE.Bone;
    Joint_16_Object_10_SINGLE: THREE.Bone;
    Joint_16_Object_11_SINGLE: THREE.Bone;
    Joint_16_Object_12_SINGLE: THREE.Bone;
    Joint_16_Object_13_SINGLE: THREE.Bone;
    Joint_16_Object_14_SINGLE: THREE.Bone;
    Joint_16_Object_15_SINGLE: THREE.Bone;
    Joint_16_Object_16_SINGLE: THREE.Bone;
    Joint_17_Object_0_SINGLE: THREE.Bone;
    Joint_17_Object_1_SINGLE: THREE.Bone;
    Joint_18_Object_0_SINGLE: THREE.Bone;
    Joint_18_Object_1_SINGLE: THREE.Bone;
    Joint_18_Object_2_SINGLE: THREE.Bone;
    Joint_18_Object_3_SINGLE: THREE.Bone;
    Joint_18_Object_4_SINGLE: THREE.Bone;
    Joint_18_Object_5_SINGLE: THREE.Bone;
    Joint_18_Object_6_SINGLE: THREE.Bone;
    Joint_18_Object_7_SINGLE: THREE.Bone;
    Joint_18_Object_8_SINGLE: THREE.Bone;
    Joint_18_Object_9_SINGLE: THREE.Bone;
    Joint_18_Object_10_SINGLE: THREE.Bone;
    Joint_18_Object_11_SINGLE: THREE.Bone;
    Joint_18_Object_12_SINGLE: THREE.Bone;
    Joint_18_Object_13_SINGLE: THREE.Bone;
    Joint_18_Object_14_SINGLE: THREE.Bone;
    Joint_18_Object_15_SINGLE: THREE.Bone;
    Joint_18_Object_16_SINGLE: THREE.Bone;
    Joint_19_Object_0_SINGLE: THREE.Bone;
    Joint_19_Object_1_SINGLE: THREE.Bone;
    Joint_20_Object_0_SINGLE: THREE.Bone;
    Joint_20_Object_1_SINGLE: THREE.Bone;
  };
  materials: {
    ["Joint_1_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_10_Material_10.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_11_Material_11.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_12_Material_12.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_15_Material_15.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_17_Material_17.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_1_Material_1.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_17_Material_17.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_2_Material_2.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_3_Material_3.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_3_Object_6_Material_6.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_10_Material_10.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_11_Material_11.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_12_Material_12.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_13_Material_13.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_17_Material_17.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_18_Material_18.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_19_Material_19.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_1_Material_1.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_2_Material_2.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_3_Material_3.001"]: THREE.MeshBasicMaterial;
    ["Joint_4_Object_3_Material_3.001"]: THREE.MeshBasicMaterial;
    ["Joint_6_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_6_Object_1_Material_1.001"]: THREE.MeshBasicMaterial;
    ["Joint_7_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
  };
  animations: GLTFAction[];
};
interface GLTFAction extends THREE.AnimationClip {
  name: never;
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<
    JSX.IntrinsicElements["skinnedMesh"] | JSX.IntrinsicElements["bone"]
  >
>;

export function Yoshisstory(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/yoshisstory.glb") as GLTFResult;
  return (
    <group {...props} scale={0.7} dispose={null}>
      <primitive object={nodes.JOBJ_0} />
      <primitive object={nodes.Joint_1_Object_0_SINGLE} />
      <primitive object={nodes.Joint_1_Object_1_SINGLE} />
      <primitive object={nodes.Joint_2_Object_0_SINGLE} />
      <primitive object={nodes.Joint_2_Object_1_SINGLE} />
      <primitive object={nodes.Joint_3_Object_0_SINGLE} />
      <primitive object={nodes.Joint_3_Object_1_SINGLE} />
      <primitive object={nodes.Joint_3_Object_2_SINGLE} />
      <primitive object={nodes.Joint_3_Object_3_SINGLE} />
      <primitive object={nodes.Joint_3_Object_4_SINGLE} />
      <primitive object={nodes.Joint_3_Object_5_SINGLE} />
      <primitive object={nodes.Joint_3_Object_6_SINGLE} />
      <primitive object={nodes.Joint_3_Object_7_SINGLE} />
      <primitive object={nodes.Joint_3_Object_8_SINGLE} />
      <primitive object={nodes.Joint_3_Object_9_SINGLE} />
      <primitive object={nodes.Joint_3_Object_10_SINGLE} />
      <primitive object={nodes.Joint_3_Object_11_SINGLE} />
      <primitive object={nodes.Joint_3_Object_12_SINGLE} />
      <primitive object={nodes.Joint_3_Object_13_SINGLE} />
      <primitive object={nodes.Joint_3_Object_14_SINGLE} />
      <primitive object={nodes.Joint_3_Object_15_SINGLE} />
      <primitive object={nodes.Joint_3_Object_16_SINGLE} />
      <primitive object={nodes.Joint_3_Object_17_SINGLE} />
      <primitive object={nodes.Joint_3_Object_18_SINGLE} />
      <primitive object={nodes.Joint_3_Object_19_SINGLE} />
      <primitive object={nodes.Joint_3_Object_20_SINGLE} />
      <primitive object={nodes.Joint_3_Object_21_SINGLE} />
      <primitive object={nodes.Joint_3_Object_22_SINGLE} />
      <primitive object={nodes.Joint_3_Object_23_SINGLE} />
      <primitive object={nodes.Joint_3_Object_24_SINGLE} />
      <primitive object={nodes.Joint_3_Object_25_SINGLE} />
      <primitive object={nodes.Joint_4_Object_0_SINGLE} />
      <primitive object={nodes.Joint_4_Object_1_SINGLE} />
      <primitive object={nodes.Joint_4_Object_2_SINGLE} />
      <primitive object={nodes.Joint_4_Object_3_SINGLE} />
      <primitive object={nodes.Joint_4_Object_4_SINGLE} />
      <primitive object={nodes.Joint_4_Object_5_SINGLE} />
      <primitive object={nodes.Joint_4_Object_6_SINGLE} />
      <primitive object={nodes.Joint_4_Object_7_SINGLE} />
      <primitive object={nodes.Joint_4_Object_8_SINGLE} />
      <primitive object={nodes.Joint_4_Object_9_SINGLE} />
      <primitive object={nodes.Joint_4_Object_10_SINGLE} />
      <primitive object={nodes.Joint_4_Object_11_SINGLE} />
      <primitive object={nodes.Joint_4_Object_12_SINGLE} />
      <primitive object={nodes.Joint_4_Object_13_SINGLE} />
      <primitive object={nodes.Joint_4_Object_14_SINGLE} />
      <primitive object={nodes.Joint_4_Object_15_SINGLE} />
      <primitive object={nodes.Joint_4_Object_16_SINGLE} />
      <primitive object={nodes.Joint_4_Object_17_SINGLE} />
      <primitive object={nodes.Joint_4_Object_18_SINGLE} />
      <primitive object={nodes.Joint_4_Object_19_SINGLE} />
      <primitive object={nodes.Joint_6_Object_0_SINGLE} />
      <primitive object={nodes.Joint_6_Object_1_SINGLE} />
      <primitive object={nodes.Joint_7_Object_0_SINGLE} />
      <primitive object={nodes.Joint_7_Object_1_SINGLE} />
      <primitive object={nodes.Joint_12_Object_0_SINGLE} />
      <primitive object={nodes.Joint_12_Object_1_SINGLE} />
      <primitive object={nodes.Joint_13_Object_0_SINGLE} />
      <primitive object={nodes.Joint_13_Object_1_SINGLE} />
      <primitive object={nodes.Joint_14_Object_0_SINGLE} />
      <primitive object={nodes.Joint_14_Object_1_SINGLE} />
      <primitive object={nodes.Joint_15_Object_0_SINGLE} />
      <primitive object={nodes.Joint_15_Object_1_SINGLE} />
      <primitive object={nodes.Joint_16_Object_0_SINGLE} />
      <primitive object={nodes.Joint_16_Object_1_SINGLE} />
      <primitive object={nodes.Joint_16_Object_2_SINGLE} />
      <primitive object={nodes.Joint_16_Object_3_SINGLE} />
      <primitive object={nodes.Joint_16_Object_4_SINGLE} />
      <primitive object={nodes.Joint_16_Object_5_SINGLE} />
      <primitive object={nodes.Joint_16_Object_6_SINGLE} />
      <primitive object={nodes.Joint_16_Object_7_SINGLE} />
      <primitive object={nodes.Joint_16_Object_8_SINGLE} />
      <primitive object={nodes.Joint_16_Object_9_SINGLE} />
      <primitive object={nodes.Joint_16_Object_10_SINGLE} />
      <primitive object={nodes.Joint_16_Object_11_SINGLE} />
      <primitive object={nodes.Joint_16_Object_12_SINGLE} />
      <primitive object={nodes.Joint_16_Object_13_SINGLE} />
      <primitive object={nodes.Joint_16_Object_14_SINGLE} />
      <primitive object={nodes.Joint_16_Object_15_SINGLE} />
      <primitive object={nodes.Joint_16_Object_16_SINGLE} />
      <primitive object={nodes.Joint_17_Object_0_SINGLE} />
      <primitive object={nodes.Joint_17_Object_1_SINGLE} />
      <primitive object={nodes.Joint_18_Object_0_SINGLE} />
      <primitive object={nodes.Joint_18_Object_1_SINGLE} />
      <primitive object={nodes.Joint_18_Object_2_SINGLE} />
      <primitive object={nodes.Joint_18_Object_3_SINGLE} />
      <primitive object={nodes.Joint_18_Object_4_SINGLE} />
      <primitive object={nodes.Joint_18_Object_5_SINGLE} />
      <primitive object={nodes.Joint_18_Object_6_SINGLE} />
      <primitive object={nodes.Joint_18_Object_7_SINGLE} />
      <primitive object={nodes.Joint_18_Object_8_SINGLE} />
      <primitive object={nodes.Joint_18_Object_9_SINGLE} />
      <primitive object={nodes.Joint_18_Object_10_SINGLE} />
      <primitive object={nodes.Joint_18_Object_11_SINGLE} />
      <primitive object={nodes.Joint_18_Object_12_SINGLE} />
      <primitive object={nodes.Joint_18_Object_13_SINGLE} />
      <primitive object={nodes.Joint_18_Object_14_SINGLE} />
      <primitive object={nodes.Joint_18_Object_15_SINGLE} />
      <primitive object={nodes.Joint_18_Object_16_SINGLE} />
      <primitive object={nodes.Joint_19_Object_0_SINGLE} />
      <primitive object={nodes.Joint_19_Object_1_SINGLE} />
      <primitive object={nodes.Joint_20_Object_0_SINGLE} />
      <primitive object={nodes.Joint_20_Object_1_SINGLE} />
      <skinnedMesh
        geometry={nodes.mesh_0.geometry}
        material={materials["Joint_1_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_0.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_1.geometry}
        material={materials["Joint_3_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_1.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_2.geometry}
        material={materials["Joint_3_Object_10_Material_10.001"]}
        skeleton={nodes.mesh_2.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_3.geometry}
        material={materials["Joint_3_Object_11_Material_11.001"]}
        skeleton={nodes.mesh_3.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_4.geometry}
        material={materials["Joint_3_Object_12_Material_12.001"]}
        skeleton={nodes.mesh_4.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_5.geometry}
        material={materials["Joint_3_Object_15_Material_15.001"]}
        skeleton={nodes.mesh_5.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_6.geometry}
        material={materials["Joint_3_Object_17_Material_17.001"]}
        skeleton={nodes.mesh_6.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_7.geometry}
        material={materials["Joint_3_Object_1_Material_1.001"]}
        skeleton={nodes.mesh_7.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_8.geometry}
        material={materials["Joint_3_Object_17_Material_17.001"]}
        skeleton={nodes.mesh_8.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_9.geometry}
        material={materials["Joint_3_Object_2_Material_2.001"]}
        skeleton={nodes.mesh_9.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_10.geometry}
        material={materials["Joint_3_Object_3_Material_3.001"]}
        skeleton={nodes.mesh_10.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_11.geometry}
        material={materials["Joint_3_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_11.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_12.geometry}
        material={materials["Joint_3_Object_6_Material_6.001"]}
        skeleton={nodes.mesh_12.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_13.geometry}
        material={materials["Joint_4_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_13.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_14.geometry}
        material={materials["Joint_4_Object_10_Material_10.001"]}
        skeleton={nodes.mesh_14.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_15.geometry}
        material={materials["Joint_4_Object_11_Material_11.001"]}
        skeleton={nodes.mesh_15.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_16.geometry}
        material={materials["Joint_4_Object_12_Material_12.001"]}
        skeleton={nodes.mesh_16.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_17.geometry}
        material={materials["Joint_4_Object_13_Material_13.001"]}
        skeleton={nodes.mesh_17.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_18.geometry}
        material={materials["Joint_4_Object_17_Material_17.001"]}
        skeleton={nodes.mesh_18.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_19.geometry}
        material={materials["Joint_4_Object_18_Material_18.001"]}
        skeleton={nodes.mesh_19.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_20.geometry}
        material={materials["Joint_4_Object_19_Material_19.001"]}
        skeleton={nodes.mesh_20.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_21.geometry}
        material={materials["Joint_4_Object_1_Material_1.001"]}
        skeleton={nodes.mesh_21.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_22.geometry}
        material={materials["Joint_4_Object_2_Material_2.001"]}
        skeleton={nodes.mesh_22.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_23.geometry}
        material={materials["Joint_4_Object_3_Material_3.001"]}
        skeleton={nodes.mesh_23.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_24.geometry}
        material={materials["Joint_4_Object_3_Material_3.001"]}
        skeleton={nodes.mesh_24.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_25.geometry}
        material={materials["Joint_6_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_25.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_26.geometry}
        material={materials["Joint_6_Object_1_Material_1.001"]}
        skeleton={nodes.mesh_26.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <skinnedMesh
        geometry={nodes.mesh_27.geometry}
        material={materials["Joint_7_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_27.skeleton}
        position={[-140.25, 80, -300]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.023}
      />
    </group>
  );
}

useGLTF.preload("/yoshisstory.glb");
