// Generated by Wrangler on Fri Mar 22 2024 18:42:25 GMT+0100 (Central European Standard Time)
// by running `wrangler types`

interface Env {
  BUCKET: R2Bucket;
  DB: D1Database;
  DBSTAGING: D1Database;
}
