import ATTACKAIRB from "./ATTACKAIRB.json";
import DAMAGEN2 from "./DAMAGEN2.json";
import FALLAERIAL from "./FALLAERIAL.json";
import LANDINGFALLSPECIAL from "./LANDINGFALLSPECIAL.json";
import SIDESPECIALGROUND from "./SIDESPECIALGROUND.json";
import THROWNFOXUP from "./THROWNFOXUP.json";
import ATTACKAIRD from "./ATTACKAIRD.json";
import DASH from "./DASH.json";
import FALLSPECIAL from "./FALLSPECIAL.json";
import MISSFOOT from "./MISSFOOT.json";
import SIDESPECIALGROUND2FORWARD from "./SIDESPECIALGROUND2FORWARD.json";
import THROWNMARTHBACK from "./THROWNMARTHBACK.json";
import ATTACKAIRF from "./ATTACKAIRF.json";
import DEADDOWN from "./DEADDOWN.json";
import FORWARDSMASH from "./FORWARDSMASH.json";
import NEUTRALSPECIALAIR from "./NEUTRALSPECIALAIR.json";
import SIDESPECIALGROUND2UP from "./SIDESPECIALGROUND2UP.json";
import THROWNMARTHDOWN from "./THROWNMARTHDOWN.json";
import ATTACKAIRN from "./ATTACKAIRN.json";
import DEADLEFT from "./DEADLEFT.json";
import FORWARDTILT from "./FORWARDTILT.json";
import NEUTRALSPECIALGROUND from "./NEUTRALSPECIALGROUND.json";
import SIDESPECIALGROUND3DOWN from "./SIDESPECIALGROUND3DOWN.json";
import THROWNMARTHFORWARD from "./THROWNMARTHFORWARD.json";
import ATTACKAIRU from "./ATTACKAIRU.json";
import DEADRIGHT from "./DEADRIGHT.json";
import FURAFURA from "./FURAFURA.json";
import OTTOTTO from "./OTTOTTO.json";
import SIDESPECIALGROUND3FORWARD from "./SIDESPECIALGROUND3FORWARD.json";
import THROWNMARTHUP from "./THROWNMARTHUP.json";
import ATTACKDASH from "./ATTACKDASH.json";
import DEADUP from "./DEADUP.json";
import FURASLEEPEND from "./FURASLEEPEND.json";
import OTTOTTOWAIT from "./OTTOTTOWAIT.json";
import SIDESPECIALGROUND3UP from "./SIDESPECIALGROUND3UP.json";
import THROWNPUFFBACK from "./THROWNPUFFBACK.json";
import CAPTURECUT from "./CAPTURECUT.json";
import DOWNATTACK from "./DOWNATTACK.json";
import FURASLEEPLOOP from "./FURASLEEPLOOP.json";
import PASS from "./PASS.json";
import SIDESPECIALGROUND4DOWN from "./SIDESPECIALGROUND4DOWN.json";
import THROWNPUFFDOWN from "./THROWNPUFFDOWN.json";
import CAPTUREDAMAGE from "./CAPTUREDAMAGE.json";
import DOWNBOUND from "./DOWNBOUND.json";
import FURASLEEPSTART from "./FURASLEEPSTART.json";
import REBIRTH from "./REBIRTH.json";
import SIDESPECIALGROUND4FORWARD from "./SIDESPECIALGROUND4FORWARD.json";
import THROWNPUFFFORWARD from "./THROWNPUFFFORWARD.json";
import CAPTUREPULLED from "./CAPTUREPULLED.json";
import DOWNDAMAGE from "./DOWNDAMAGE.json";
import GRAB from "./GRAB.json";
import REBIRTHWAIT from "./REBIRTHWAIT.json";
import SIDESPECIALGROUND4UP from "./SIDESPECIALGROUND4UP.json";
import THROWNPUFFUP from "./THROWNPUFFUP.json";
import CAPTUREWAIT from "./CAPTUREWAIT.json";
import DOWNSMASH from "./DOWNSMASH.json";
import GUARD from "./GUARD.json";
import REBOUND from "./REBOUND.json";
import SLEEP from "./SLEEP.json";
import THROWUP from "./THROWUP.json";
import CATCHATTACK from "./CATCHATTACK.json";
import DOWNSPECIALAIR from "./DOWNSPECIALAIR.json";
import GUARDOFF from "./GUARDOFF.json";
import RUN from "./RUN.json";
import SMASHTURN from "./SMASHTURN.json";
import TILTTURN from "./TILTTURN.json";
import CATCHCUT from "./CATCHCUT.json";
import DOWNSPECIALAIR2 from "./DOWNSPECIALAIR2.json";
import GUARDON from "./GUARDON.json";
import RUNBRAKE from "./RUNBRAKE.json";
import SQUAT from "./SQUAT.json";
import UPSMASH from "./UPSMASH.json";
import CATCHWAIT from "./CATCHWAIT.json";
import DOWNSPECIALGROUND from "./DOWNSPECIALGROUND.json";
import JAB1 from "./JAB1.json";
import RUNTURN from "./RUNTURN.json";
import SQUATRV from "./SQUATRV.json";
import UPSPECIAL from "./UPSPECIAL.json";
import CLIFFATTACKQUICK from "./CLIFFATTACKQUICK.json";
import DOWNSPECIALGROUND2 from "./DOWNSPECIALGROUND2.json";
import JAB2 from "./JAB2.json";
import SHIELDBREAKDOWNBOUND from "./SHIELDBREAKDOWNBOUND.json";
import SQUATWAIT from "./SQUATWAIT.json";
import UPTILT from "./UPTILT.json";
import CLIFFATTACKSLOW from "./CLIFFATTACKSLOW.json";
import DOWNSTANDB from "./DOWNSTANDB.json";
import JUMPAERIALB from "./JUMPAERIALB.json";
import SHIELDBREAKFALL from "./SHIELDBREAKFALL.json";
import STOPCEIL from "./STOPCEIL.json";
import WAIT from "./WAIT.json";
import CLIFFCATCH from "./CLIFFCATCH.json";
import DOWNSTANDF from "./DOWNSTANDF.json";
import JUMPAERIALF from "./JUMPAERIALF.json";
import SHIELDBREAKSTAND from "./SHIELDBREAKSTAND.json";
import TECHB from "./TECHB.json";
import WALK from "./WALK.json";
import CLIFFESCAPEQUICK from "./CLIFFESCAPEQUICK.json";
import DOWNSTANDN from "./DOWNSTANDN.json";
import JUMPB from "./JUMPB.json";
import SIDESPECIALAIR from "./SIDESPECIALAIR.json";
import TECHF from "./TECHF.json";
import WALLDAMAGE from "./WALLDAMAGE.json";
import CLIFFESCAPESLOW from "./CLIFFESCAPESLOW.json";
import DOWNTILT from "./DOWNTILT.json";
import JUMPF from "./JUMPF.json";
import SIDESPECIALAIR2FORWARD from "./SIDESPECIALAIR2FORWARD.json";
import TECHN from "./TECHN.json";
import WALLJUMP from "./WALLJUMP.json";
import CLIFFGETUPQUICK from "./CLIFFGETUPQUICK.json";
import DOWNWAIT from "./DOWNWAIT.json";
import KNEEBEND from "./KNEEBEND.json";
import SIDESPECIALAIR2UP from "./SIDESPECIALAIR2UP.json";
import TECHU from "./TECHU.json";
import WALLTECH from "./WALLTECH.json";
import CLIFFGETUPSLOW from "./CLIFFGETUPSLOW.json";
import ENTRANCE from "./ENTRANCE.json";
import LANDING from "./LANDING.json";
import SIDESPECIALAIR3DOWN from "./SIDESPECIALAIR3DOWN.json";
import THROWBACK from "./THROWBACK.json";
import WALLTECHJUMP from "./WALLTECHJUMP.json";
import CLIFFJUMPQUICK from "./CLIFFJUMPQUICK.json";
import ESCAPEAIR from "./ESCAPEAIR.json";
import LANDINGATTACKAIRB from "./LANDINGATTACKAIRB.json";
import SIDESPECIALAIR3FORWARD from "./SIDESPECIALAIR3FORWARD.json";
import THROWDOWN from "./THROWDOWN.json";
import CLIFFJUMPSLOW from "./CLIFFJUMPSLOW.json";
import ESCAPEB from "./ESCAPEB.json";
import LANDINGATTACKAIRD from "./LANDINGATTACKAIRD.json";
import SIDESPECIALAIR3UP from "./SIDESPECIALAIR3UP.json";
import THROWFORWARD from "./THROWFORWARD.json";
import CLIFFWAIT from "./CLIFFWAIT.json";
import ESCAPEF from "./ESCAPEF.json";
import LANDINGATTACKAIRF from "./LANDINGATTACKAIRF.json";
import SIDESPECIALAIR4DOWN from "./SIDESPECIALAIR4DOWN.json";
import THROWNFOXBACK from "./THROWNFOXBACK.json";
import DAMAGEFALL from "./DAMAGEFALL.json";
import ESCAPEN from "./ESCAPEN.json";
import LANDINGATTACKAIRN from "./LANDINGATTACKAIRN.json";
import SIDESPECIALAIR4FORWARD from "./SIDESPECIALAIR4FORWARD.json";
import THROWNFOXDOWN from "./THROWNFOXDOWN.json";
import DAMAGEFLYN from "./DAMAGEFLYN.json";
import FALL from "./FALL.json";
import LANDINGATTACKAIRU from "./LANDINGATTACKAIRU.json";
import SIDESPECIALAIR4UP from "./SIDESPECIALAIR4UP.json";
import THROWNFOXFORWARD from "./THROWNFOXFORWARD.json";
import THROWNFALCOBACK from "./THROWNFALCOBACK.json";
import THROWNFALCODOWN from "./THROWNFALCODOWN.json";
import THROWNFALCOFORWARD from "./THROWNFALCOFORWARD.json";
import THROWNFALCOUP from "./THROWNFALCOUP.json";
import THROWNFALCONBACK from "./THROWNFALCONBACK.json";
import THROWNFALCONDOWN from "./THROWNFALCONDOWN.json";
import THROWNFALCONFORWARD from "./THROWNFALCONFORWARD.json";
import THROWNFALCONUP from "./THROWNFALCONUP.json";
import APPEAL from "./APPEAL.json";
import THROWNFALCONDIVE from "./THROWNFALCONDIVE.json";

export default {
  ATTACKAIRB: ATTACKAIRB,
  DAMAGEN2: DAMAGEN2,
  FALLAERIAL: FALLAERIAL,
  LANDINGFALLSPECIAL: LANDINGFALLSPECIAL,
  SIDESPECIALGROUND: SIDESPECIALGROUND,
  THROWNFOXUP: THROWNFOXUP,
  ATTACKAIRD: ATTACKAIRD,
  DASH: DASH,
  FALLSPECIAL: FALLSPECIAL,
  MISSFOOT: MISSFOOT,
  SIDESPECIALGROUND2FORWARD: SIDESPECIALGROUND2FORWARD,
  THROWNMARTHBACK: THROWNMARTHBACK,
  ATTACKAIRF: ATTACKAIRF,
  DEADDOWN: DEADDOWN,
  FORWARDSMASH: FORWARDSMASH,
  NEUTRALSPECIALAIR: NEUTRALSPECIALAIR,
  SIDESPECIALGROUND2UP: SIDESPECIALGROUND2UP,
  THROWNMARTHDOWN: THROWNMARTHDOWN,
  ATTACKAIRN: ATTACKAIRN,
  DEADLEFT: DEADLEFT,
  FORWARDTILT: FORWARDTILT,
  NEUTRALSPECIALGROUND: NEUTRALSPECIALGROUND,
  SIDESPECIALGROUND3DOWN: SIDESPECIALGROUND3DOWN,
  THROWNMARTHFORWARD: THROWNMARTHFORWARD,
  ATTACKAIRU: ATTACKAIRU,
  DEADRIGHT: DEADRIGHT,
  FURAFURA: FURAFURA,
  OTTOTTO: OTTOTTO,
  SIDESPECIALGROUND3FORWARD: SIDESPECIALGROUND3FORWARD,
  THROWNMARTHUP: THROWNMARTHUP,
  ATTACKDASH: ATTACKDASH,
  DEADUP: DEADUP,
  FURASLEEPEND: FURASLEEPEND,
  OTTOTTOWAIT: OTTOTTOWAIT,
  SIDESPECIALGROUND3UP: SIDESPECIALGROUND3UP,
  THROWNPUFFBACK: THROWNPUFFBACK,
  CAPTURECUT: CAPTURECUT,
  DOWNATTACK: DOWNATTACK,
  FURASLEEPLOOP: FURASLEEPLOOP,
  PASS: PASS,
  SIDESPECIALGROUND4DOWN: SIDESPECIALGROUND4DOWN,
  THROWNPUFFDOWN: THROWNPUFFDOWN,
  CAPTUREDAMAGE: CAPTUREDAMAGE,
  DOWNBOUND: DOWNBOUND,
  FURASLEEPSTART: FURASLEEPSTART,
  REBIRTH: REBIRTH,
  SIDESPECIALGROUND4FORWARD: SIDESPECIALGROUND4FORWARD,
  THROWNPUFFFORWARD: THROWNPUFFFORWARD,
  CAPTUREPULLED: CAPTUREPULLED,
  DOWNDAMAGE: DOWNDAMAGE,
  GRAB: GRAB,
  REBIRTHWAIT: REBIRTHWAIT,
  SIDESPECIALGROUND4UP: SIDESPECIALGROUND4UP,
  THROWNPUFFUP: THROWNPUFFUP,
  CAPTUREWAIT: CAPTUREWAIT,
  DOWNSMASH: DOWNSMASH,
  GUARD: GUARD,
  REBOUND: REBOUND,
  SLEEP: SLEEP,
  THROWUP: THROWUP,
  CATCHATTACK: CATCHATTACK,
  DOWNSPECIALAIR: DOWNSPECIALAIR,
  GUARDOFF: GUARDOFF,
  RUN: RUN,
  SMASHTURN: SMASHTURN,
  TILTTURN: TILTTURN,
  CATCHCUT: CATCHCUT,
  DOWNSPECIALAIR2: DOWNSPECIALAIR2,
  GUARDON: GUARDON,
  RUNBRAKE: RUNBRAKE,
  SQUAT: SQUAT,
  UPSMASH: UPSMASH,
  CATCHWAIT: CATCHWAIT,
  DOWNSPECIALGROUND: DOWNSPECIALGROUND,
  JAB1: JAB1,
  RUNTURN: RUNTURN,
  SQUATRV: SQUATRV,
  UPSPECIAL: UPSPECIAL,
  CLIFFATTACKQUICK: CLIFFATTACKQUICK,
  DOWNSPECIALGROUND2: DOWNSPECIALGROUND2,
  JAB2: JAB2,
  SHIELDBREAKDOWNBOUND: SHIELDBREAKDOWNBOUND,
  SQUATWAIT: SQUATWAIT,
  UPTILT: UPTILT,
  CLIFFATTACKSLOW: CLIFFATTACKSLOW,
  DOWNSTANDB: DOWNSTANDB,
  JUMPAERIALB: JUMPAERIALB,
  SHIELDBREAKFALL: SHIELDBREAKFALL,
  STOPCEIL: STOPCEIL,
  WAIT: WAIT,
  CLIFFCATCH: CLIFFCATCH,
  DOWNSTANDF: DOWNSTANDF,
  JUMPAERIALF: JUMPAERIALF,
  SHIELDBREAKSTAND: SHIELDBREAKSTAND,
  TECHB: TECHB,
  WALK: WALK,
  CLIFFESCAPEQUICK: CLIFFESCAPEQUICK,
  DOWNSTANDN: DOWNSTANDN,
  JUMPB: JUMPB,
  SIDESPECIALAIR: SIDESPECIALAIR,
  TECHF: TECHF,
  WALLDAMAGE: WALLDAMAGE,
  CLIFFESCAPESLOW: CLIFFESCAPESLOW,
  DOWNTILT: DOWNTILT,
  JUMPF: JUMPF,
  SIDESPECIALAIR2FORWARD: SIDESPECIALAIR2FORWARD,
  TECHN: TECHN,
  WALLJUMP: WALLJUMP,
  CLIFFGETUPQUICK: CLIFFGETUPQUICK,
  DOWNWAIT: DOWNWAIT,
  KNEEBEND: KNEEBEND,
  SIDESPECIALAIR2UP: SIDESPECIALAIR2UP,
  TECHU: TECHU,
  WALLTECH: WALLTECH,
  CLIFFGETUPSLOW: CLIFFGETUPSLOW,
  ENTRANCE: ENTRANCE,
  LANDING: LANDING,
  SIDESPECIALAIR3DOWN: SIDESPECIALAIR3DOWN,
  THROWBACK: THROWBACK,
  WALLTECHJUMP: WALLTECHJUMP,
  CLIFFJUMPQUICK: CLIFFJUMPQUICK,
  ESCAPEAIR: ESCAPEAIR,
  LANDINGATTACKAIRB: LANDINGATTACKAIRB,
  SIDESPECIALAIR3FORWARD: SIDESPECIALAIR3FORWARD,
  THROWDOWN: THROWDOWN,
  CLIFFJUMPSLOW: CLIFFJUMPSLOW,
  ESCAPEB: ESCAPEB,
  LANDINGATTACKAIRD: LANDINGATTACKAIRD,
  SIDESPECIALAIR3UP: SIDESPECIALAIR3UP,
  THROWFORWARD: THROWFORWARD,
  CLIFFWAIT: CLIFFWAIT,
  ESCAPEF: ESCAPEF,
  LANDINGATTACKAIRF: LANDINGATTACKAIRF,
  SIDESPECIALAIR4DOWN: SIDESPECIALAIR4DOWN,
  THROWNFOXBACK: THROWNFOXBACK,
  DAMAGEFALL: DAMAGEFALL,
  ESCAPEN: ESCAPEN,
  LANDINGATTACKAIRN: LANDINGATTACKAIRN,
  SIDESPECIALAIR4FORWARD: SIDESPECIALAIR4FORWARD,
  THROWNFOXDOWN: THROWNFOXDOWN,
  DAMAGEFLYN: DAMAGEFLYN,
  FALL: FALL,
  LANDINGATTACKAIRU: LANDINGATTACKAIRU,
  SIDESPECIALAIR4UP: SIDESPECIALAIR4UP,
  THROWNFOXFORWARD: THROWNFOXFORWARD,
  THROWNFALCOBACK: THROWNFALCOBACK,
  THROWNFALCODOWN: THROWNFALCODOWN,
  THROWNFALCOFORWARD: THROWNFALCOFORWARD,
  THROWNFALCOUP: THROWNFALCOUP,
  THROWNFALCONBACK: THROWNFALCONBACK,
  THROWNFALCONDOWN: THROWNFALCONDOWN,
  THROWNFALCONFORWARD: THROWNFALCONFORWARD,
  THROWNFALCONUP: THROWNFALCONUP,
  APPEAL: APPEAL,
  THROWNFALCONDIVE: THROWNFALCONDIVE,
};
