import ATTACKAIRB from "./ATTACKAIRB.json";
import CLIFFESCAPESLOW from "./CLIFFESCAPESLOW.json";
import DOWNSMASH from "./DOWNSMASH.json";
import FALLSPECIAL from "./FALLSPECIAL.json";
import JUMPB from "./JUMPB.json";
import REBIRTHWAIT from "./REBIRTHWAIT.json";
import TECHF from "./TECHF.json";
import THROWNPUFFUP from "./THROWNPUFFUP.json";
import ATTACKAIRD from "./ATTACKAIRD.json";
import CLIFFGETUPQUICK from "./CLIFFGETUPQUICK.json";
import DOWNSPECIALAIR from "./DOWNSPECIALAIR.json";
import FIREFOXBOUNCE from "./FIREFOXBOUNCE.json";
import JUMPF from "./JUMPF.json";
import REBOUND from "./REBOUND.json";
import TECHN from "./TECHN.json";
import THROWUP from "./THROWUP.json";
import ATTACKAIRF from "./ATTACKAIRF.json";
import CLIFFGETUPSLOW from "./CLIFFGETUPSLOW.json";
import DOWNSPECIALGROUND from "./DOWNSPECIALGROUND.json";
import FORWARDSMASH from "./FORWARDSMASH.json";
import KNEEBEND from "./KNEEBEND.json";
import RUN from "./RUN.json";
import TECHU from "./TECHU.json";
import TILTTURN from "./TILTTURN.json";
import ATTACKAIRN from "./ATTACKAIRN.json";
import CLIFFJUMPQUICK from "./CLIFFJUMPQUICK.json";
import DOWNSTANDB from "./DOWNSTANDB.json";
import FORWARDTILT from "./FORWARDTILT.json";
import LANDING from "./LANDING.json";
import RUNBRAKE from "./RUNBRAKE.json";
import THROWBACK from "./THROWBACK.json";
import UPSMASH from "./UPSMASH.json";
import ATTACKAIRU from "./ATTACKAIRU.json";
import CLIFFJUMPSLOW from "./CLIFFJUMPSLOW.json";
import DOWNSTANDF from "./DOWNSTANDF.json";
import FURAFURA from "./FURAFURA.json";
import LANDINGATTACKAIRB from "./LANDINGATTACKAIRB.json";
import RUNTURN from "./RUNTURN.json";
import THROWDOWN from "./THROWDOWN.json";
import UPSPECIALCHARGE from "./UPSPECIALCHARGE.json";
import ATTACKDASH from "./ATTACKDASH.json";
import CLIFFWAIT from "./CLIFFWAIT.json";
import DOWNSTANDN from "./DOWNSTANDN.json";
import FURASLEEPEND from "./FURASLEEPEND.json";
import LANDINGATTACKAIRD from "./LANDINGATTACKAIRD.json";
import SHIELDBREAKDOWNBOUND from "./SHIELDBREAKDOWNBOUND.json";
import THROWFORWARD from "./THROWFORWARD.json";
import UPSPECIALLAUNCH from "./UPSPECIALLAUNCH.json";
import CAPTURECUT from "./CAPTURECUT.json";
import DAMAGEFALL from "./DAMAGEFALL.json";
import DOWNTILT from "./DOWNTILT.json";
import FURASLEEPLOOP from "./FURASLEEPLOOP.json";
import LANDINGATTACKAIRF from "./LANDINGATTACKAIRF.json";
import SHIELDBREAKFALL from "./SHIELDBREAKFALL.json";
import THROWNFOXBACK from "./THROWNFOXBACK.json";
import UPTILT from "./UPTILT.json";
import CAPTUREDAMAGE from "./CAPTUREDAMAGE.json";
import DAMAGEFLYN from "./DAMAGEFLYN.json";
import DOWNWAIT from "./DOWNWAIT.json";
import FURASLEEPSTART from "./FURASLEEPSTART.json";
import LANDINGATTACKAIRN from "./LANDINGATTACKAIRN.json";
import SHIELDBREAKSTAND from "./SHIELDBREAKSTAND.json";
import THROWNFOXDOWN from "./THROWNFOXDOWN.json";
import WAIT from "./WAIT.json";
import CAPTUREPULLED from "./CAPTUREPULLED.json";
import DAMAGEN2 from "./DAMAGEN2.json";
import ENTRANCE from "./ENTRANCE.json";
import GRAB from "./GRAB.json";
import LANDINGATTACKAIRU from "./LANDINGATTACKAIRU.json";
import SIDESPECIALAIR from "./SIDESPECIALAIR.json";
import THROWNFOXFORWARD from "./THROWNFOXFORWARD.json";
import WALK from "./WALK.json";
import CAPTUREWAIT from "./CAPTUREWAIT.json";
import DASH from "./DASH.json";
import ESCAPEAIR from "./ESCAPEAIR.json";
import GUARD from "./GUARD.json";
import LANDINGFALLSPECIAL from "./LANDINGFALLSPECIAL.json";
import SIDESPECIALGROUND from "./SIDESPECIALGROUND.json";
import THROWNFOXUP from "./THROWNFOXUP.json";
import WALLDAMAGE from "./WALLDAMAGE.json";
import CATCHATTACK from "./CATCHATTACK.json";
import DEADDOWN from "./DEADDOWN.json";
import ESCAPEB from "./ESCAPEB.json";
import GUARDOFF from "./GUARDOFF.json";
import MISSFOOT from "./MISSFOOT.json";
import SLEEP from "./SLEEP.json";
import THROWNMARTHBACK from "./THROWNMARTHBACK.json";
import WALLJUMP from "./WALLJUMP.json";
import CATCHCUT from "./CATCHCUT.json";
import DEADLEFT from "./DEADLEFT.json";
import ESCAPEF from "./ESCAPEF.json";
import GUARDON from "./GUARDON.json";
import NEUTRALSPECIALAIR from "./NEUTRALSPECIALAIR.json";
import SMASHTURN from "./SMASHTURN.json";
import THROWNMARTHDOWN from "./THROWNMARTHDOWN.json";
import WALLTECH from "./WALLTECH.json";
import CATCHWAIT from "./CATCHWAIT.json";
import DEADRIGHT from "./DEADRIGHT.json";
import ESCAPEN from "./ESCAPEN.json";
import JAB1 from "./JAB1.json";
import NEUTRALSPECIALGROUND from "./NEUTRALSPECIALGROUND.json";
import SQUAT from "./SQUAT.json";
import THROWNMARTHFORWARD from "./THROWNMARTHFORWARD.json";
import WALLTECHJUMP from "./WALLTECHJUMP.json";
import CLIFFATTACKQUICK from "./CLIFFATTACKQUICK.json";
import DEADUP from "./DEADUP.json";
import FALCONDASH from "./FALCONDASH.json";
import JAB2 from "./JAB2.json";
import OTTOTTO from "./OTTOTTO.json";
import SQUATRV from "./SQUATRV.json";
import THROWNMARTHUP from "./THROWNMARTHUP.json";
import CLIFFATTACKSLOW from "./CLIFFATTACKSLOW.json";
import DOWNATTACK from "./DOWNATTACK.json";
import FALCONKNEE from "./FALCONKNEE.json";
import JAB3 from "./JAB3.json";
import OTTOTTOWAIT from "./OTTOTTOWAIT.json";
import SQUATWAIT from "./SQUATWAIT.json";
import THROWNPUFFBACK from "./THROWNPUFFBACK.json";
import CLIFFCATCH from "./CLIFFCATCH.json";
import DOWNBOUND from "./DOWNBOUND.json";
import FALL from "./FALL.json";
import JUMPAERIALB from "./JUMPAERIALB.json";
import PASS from "./PASS.json";
import STOPCEIL from "./STOPCEIL.json";
import THROWNPUFFDOWN from "./THROWNPUFFDOWN.json";
import CLIFFESCAPEQUICK from "./CLIFFESCAPEQUICK.json";
import DOWNDAMAGE from "./DOWNDAMAGE.json";
import FALLAERIAL from "./FALLAERIAL.json";
import JUMPAERIALF from "./JUMPAERIALF.json";
import REBIRTH from "./REBIRTH.json";
import TECHB from "./TECHB.json";
import THROWNPUFFFORWARD from "./THROWNPUFFFORWARD.json";
import THROWNFALCOBACK from "./THROWNFALCOBACK.json";
import THROWNFALCODOWN from "./THROWNFALCODOWN.json";
import THROWNFALCOFORWARD from "./THROWNFALCOFORWARD.json";
import THROWNFALCOUP from "./THROWNFALCOUP.json";
import THROWNFALCONBACK from "./THROWNFALCONBACK.json";
import THROWNFALCONDOWN from "./THROWNFALCONDOWN.json";
import THROWNFALCONFORWARD from "./THROWNFALCONFORWARD.json";
import THROWNFALCONUP from "./THROWNFALCONUP.json";
import APPEAL from "./APPEAL.json";
import THROWNFALCONDIVE from "./THROWNFALCONDIVE.json";

export default {
  ATTACKAIRB: ATTACKAIRB,
  CLIFFESCAPESLOW: CLIFFESCAPESLOW,
  DOWNSMASH: DOWNSMASH,
  FALLSPECIAL: FALLSPECIAL,
  JUMPB: JUMPB,
  REBIRTHWAIT: REBIRTHWAIT,
  TECHF: TECHF,
  THROWNPUFFUP: THROWNPUFFUP,
  ATTACKAIRD: ATTACKAIRD,
  CLIFFGETUPQUICK: CLIFFGETUPQUICK,
  DOWNSPECIALAIR: DOWNSPECIALAIR,
  FIREFOXBOUNCE: FIREFOXBOUNCE,
  JUMPF: JUMPF,
  REBOUND: REBOUND,
  TECHN: TECHN,
  THROWUP: THROWUP,
  ATTACKAIRF: ATTACKAIRF,
  CLIFFGETUPSLOW: CLIFFGETUPSLOW,
  DOWNSPECIALGROUND: DOWNSPECIALGROUND,
  FORWARDSMASH: FORWARDSMASH,
  KNEEBEND: KNEEBEND,
  RUN: RUN,
  TECHU: TECHU,
  TILTTURN: TILTTURN,
  ATTACKAIRN: ATTACKAIRN,
  CLIFFJUMPQUICK: CLIFFJUMPQUICK,
  DOWNSTANDB: DOWNSTANDB,
  FORWARDTILT: FORWARDTILT,
  LANDING: LANDING,
  RUNBRAKE: RUNBRAKE,
  THROWBACK: THROWBACK,
  UPSMASH: UPSMASH,
  ATTACKAIRU: ATTACKAIRU,
  CLIFFJUMPSLOW: CLIFFJUMPSLOW,
  DOWNSTANDF: DOWNSTANDF,
  FURAFURA: FURAFURA,
  LANDINGATTACKAIRB: LANDINGATTACKAIRB,
  RUNTURN: RUNTURN,
  THROWDOWN: THROWDOWN,
  UPSPECIALCHARGE: UPSPECIALCHARGE,
  ATTACKDASH: ATTACKDASH,
  CLIFFWAIT: CLIFFWAIT,
  DOWNSTANDN: DOWNSTANDN,
  FURASLEEPEND: FURASLEEPEND,
  LANDINGATTACKAIRD: LANDINGATTACKAIRD,
  SHIELDBREAKDOWNBOUND: SHIELDBREAKDOWNBOUND,
  THROWFORWARD: THROWFORWARD,
  UPSPECIALLAUNCH: UPSPECIALLAUNCH,
  CAPTURECUT: CAPTURECUT,
  DAMAGEFALL: DAMAGEFALL,
  DOWNTILT: DOWNTILT,
  FURASLEEPLOOP: FURASLEEPLOOP,
  LANDINGATTACKAIRF: LANDINGATTACKAIRF,
  SHIELDBREAKFALL: SHIELDBREAKFALL,
  THROWNFOXBACK: THROWNFOXBACK,
  UPTILT: UPTILT,
  CAPTUREDAMAGE: CAPTUREDAMAGE,
  DAMAGEFLYN: DAMAGEFLYN,
  DOWNWAIT: DOWNWAIT,
  FURASLEEPSTART: FURASLEEPSTART,
  LANDINGATTACKAIRN: LANDINGATTACKAIRN,
  SHIELDBREAKSTAND: SHIELDBREAKSTAND,
  THROWNFOXDOWN: THROWNFOXDOWN,
  WAIT: WAIT,
  CAPTUREPULLED: CAPTUREPULLED,
  DAMAGEN2: DAMAGEN2,
  ENTRANCE: ENTRANCE,
  GRAB: GRAB,
  LANDINGATTACKAIRU: LANDINGATTACKAIRU,
  SIDESPECIALAIR: SIDESPECIALAIR,
  THROWNFOXFORWARD: THROWNFOXFORWARD,
  WALK: WALK,
  CAPTUREWAIT: CAPTUREWAIT,
  DASH: DASH,
  ESCAPEAIR: ESCAPEAIR,
  GUARD: GUARD,
  LANDINGFALLSPECIAL: LANDINGFALLSPECIAL,
  SIDESPECIALGROUND: SIDESPECIALGROUND,
  THROWNFOXUP: THROWNFOXUP,
  WALLDAMAGE: WALLDAMAGE,
  CATCHATTACK: CATCHATTACK,
  DEADDOWN: DEADDOWN,
  ESCAPEB: ESCAPEB,
  GUARDOFF: GUARDOFF,
  MISSFOOT: MISSFOOT,
  SLEEP: SLEEP,
  THROWNMARTHBACK: THROWNMARTHBACK,
  WALLJUMP: WALLJUMP,
  CATCHCUT: CATCHCUT,
  DEADLEFT: DEADLEFT,
  ESCAPEF: ESCAPEF,
  GUARDON: GUARDON,
  NEUTRALSPECIALAIR: NEUTRALSPECIALAIR,
  SMASHTURN: SMASHTURN,
  THROWNMARTHDOWN: THROWNMARTHDOWN,
  WALLTECH: WALLTECH,
  CATCHWAIT: CATCHWAIT,
  DEADRIGHT: DEADRIGHT,
  ESCAPEN: ESCAPEN,
  JAB1: JAB1,
  NEUTRALSPECIALGROUND: NEUTRALSPECIALGROUND,
  SQUAT: SQUAT,
  THROWNMARTHFORWARD: THROWNMARTHFORWARD,
  WALLTECHJUMP: WALLTECHJUMP,
  CLIFFATTACKQUICK: CLIFFATTACKQUICK,
  DEADUP: DEADUP,
  FALCONDASH: FALCONDASH,
  JAB2: JAB2,
  OTTOTTO: OTTOTTO,
  SQUATRV: SQUATRV,
  THROWNMARTHUP: THROWNMARTHUP,
  CLIFFATTACKSLOW: CLIFFATTACKSLOW,
  DOWNATTACK: DOWNATTACK,
  FALCONKNEE: FALCONKNEE,
  JAB3: JAB3,
  OTTOTTOWAIT: OTTOTTOWAIT,
  SQUATWAIT: SQUATWAIT,
  THROWNPUFFBACK: THROWNPUFFBACK,
  CLIFFCATCH: CLIFFCATCH,
  DOWNBOUND: DOWNBOUND,
  FALL: FALL,
  JUMPAERIALB: JUMPAERIALB,
  PASS: PASS,
  STOPCEIL: STOPCEIL,
  THROWNPUFFDOWN: THROWNPUFFDOWN,
  CLIFFESCAPEQUICK: CLIFFESCAPEQUICK,
  DOWNDAMAGE: DOWNDAMAGE,
  FALLAERIAL: FALLAERIAL,
  JUMPAERIALF: JUMPAERIALF,
  REBIRTH: REBIRTH,
  TECHB: TECHB,
  THROWNPUFFFORWARD: THROWNPUFFFORWARD,
  THROWNFALCOBACK: THROWNFALCOBACK,
  THROWNFALCODOWN: THROWNFALCODOWN,
  THROWNFALCOFORWARD: THROWNFALCOFORWARD,
  THROWNFALCOUP: THROWNFALCOUP,
  THROWNFALCONBACK: THROWNFALCONBACK,
  THROWNFALCONDOWN: THROWNFALCONDOWN,
  THROWNFALCONFORWARD: THROWNFALCONFORWARD,
  THROWNFALCONUP: THROWNFALCONUP,
  APPEAL: APPEAL,
  THROWNFALCONDIVE: THROWNFALCONDIVE,
};
