import AERIALTURN1 from "./AERIALTURN1.json";
import CLIFFGETUPSLOW from "./CLIFFGETUPSLOW.json";
import DOWNSTANDB from "./DOWNSTANDB.json";
import JUMPAERIAL2 from "./JUMPAERIAL2.json";
import RUNBRAKE from "./RUNBRAKE.json";
import THROWNFOXUP from "./THROWNFOXUP.json";
import AERIALTURN2 from "./AERIALTURN2.json";
import CLIFFJUMPQUICK from "./CLIFFJUMPQUICK.json";
import DOWNSTANDF from "./DOWNSTANDF.json";
import JUMPAERIAL3 from "./JUMPAERIAL3.json";
import RUNTURN from "./RUNTURN.json";
import THROWNMARTHBACK from "./THROWNMARTHBACK.json";
import AERIALTURN3 from "./AERIALTURN3.json";
import CLIFFJUMPSLOW from "./CLIFFJUMPSLOW.json";
import DOWNSTANDN from "./DOWNSTANDN.json";
import JUMPAERIAL4 from "./JUMPAERIAL4.json";
import SHIELDBREAKDOWNBOUND from "./SHIELDBREAKDOWNBOUND.json";
import THROWNMARTHDOWN from "./THROWNMARTHDOWN.json";
import AERIALTURN4 from "./AERIALTURN4.json";
import CLIFFWAIT from "./CLIFFWAIT.json";
import DOWNTILT from "./DOWNTILT.json";
import JUMPAERIAL5 from "./JUMPAERIAL5.json";
import SHIELDBREAKFALL from "./SHIELDBREAKFALL.json";
import THROWNMARTHFORWARD from "./THROWNMARTHFORWARD.json";
import AERIALTURN5 from "./AERIALTURN5.json";
import DAMAGEFALL from "./DAMAGEFALL.json";
import DOWNWAIT from "./DOWNWAIT.json";
import JUMPB from "./JUMPB.json";
import SHIELDBREAKFLY from "./SHIELDBREAKFLY.json";
import THROWNMARTHUP from "./THROWNMARTHUP.json";
import ATTACKAIRB from "./ATTACKAIRB.json";
import DAMAGEFLYHI from "./DAMAGEFLYHI.json";
import ENTRANCE from "./ENTRANCE.json";
import JUMPF from "./JUMPF.json";
import SHIELDBREAKSTAND from "./SHIELDBREAKSTAND.json";
import THROWNPUFFBACK from "./THROWNPUFFBACK.json";
import ATTACKAIRD from "./ATTACKAIRD.json";
import DAMAGEFLYLW from "./DAMAGEFLYLW.json";
import ESCAPEAIR from "./ESCAPEAIR.json";
import KNEEBEND from "./KNEEBEND.json";
import SIDESPECIALAIR from "./SIDESPECIALAIR.json";
import THROWNPUFFDOWN from "./THROWNPUFFDOWN.json";
import ATTACKAIRF from "./ATTACKAIRF.json";
import DAMAGEFLYN from "./DAMAGEFLYN.json";
import ESCAPEB from "./ESCAPEB.json";
import LANDING from "./LANDING.json";
import SIDESPECIALGROUND from "./SIDESPECIALGROUND.json";
import THROWNPUFFFORWARD from "./THROWNPUFFFORWARD.json";
import ATTACKAIRN from "./ATTACKAIRN.json";
import DAMAGEFLYTOP from "./DAMAGEFLYTOP.json";
import ESCAPEF from "./ESCAPEF.json";
import LANDINGATTACKAIRB from "./LANDINGATTACKAIRB.json";
import SLEEP from "./SLEEP.json";
import THROWNPUFFUP from "./THROWNPUFFUP.json";
import ATTACKAIRU from "./ATTACKAIRU.json";
import DAMAGEHI1 from "./DAMAGEHI1.json";
import ESCAPEN from "./ESCAPEN.json";
import LANDINGATTACKAIRD from "./LANDINGATTACKAIRD.json";
import SMASHTURN from "./SMASHTURN.json";
import THROWUP from "./THROWUP.json";
import ATTACKDASH from "./ATTACKDASH.json";
import DAMAGEHI2 from "./DAMAGEHI2.json";
import FALL from "./FALL.json";
import LANDINGATTACKAIRF from "./LANDINGATTACKAIRF.json";
import SQUAT from "./SQUAT.json";
import TILTTURN from "./TILTTURN.json";
import CAPTURECUT from "./CAPTURECUT.json";
import DAMAGEHI3 from "./DAMAGEHI3.json";
import FALLSPECIAL from "./FALLSPECIAL.json";
import LANDINGATTACKAIRN from "./LANDINGATTACKAIRN.json";
import SQUATRV from "./SQUATRV.json";
import UPSMASH from "./UPSMASH.json";
import CAPTUREDAMAGE from "./CAPTUREDAMAGE.json";
import DAMAGEN2 from "./DAMAGEN2.json";
import FORWARDSMASH from "./FORWARDSMASH.json";
import LANDINGATTACKAIRU from "./LANDINGATTACKAIRU.json";
import SQUATWAIT from "./SQUATWAIT.json";
import UPSPECIAL from "./UPSPECIAL.json";
import CAPTUREPULLED from "./CAPTUREPULLED.json";
import DASH from "./DASH.json";
import FORWARDTILT from "./FORWARDTILT.json";
import LANDINGFALLSPECIAL from "./LANDINGFALLSPECIAL.json";
import STOPCEIL from "./STOPCEIL.json";
import UPTILT from "./UPTILT.json";
import CAPTUREWAIT from "./CAPTUREWAIT.json";
import DEADDOWN from "./DEADDOWN.json";
import FURASLEEPEND from "./FURASLEEPEND.json";
import MISSFOOT from "./MISSFOOT.json";
import TECHB from "./TECHB.json";
import WAIT from "./WAIT.json";
import CATCHATTACK from "./CATCHATTACK.json";
import DEADLEFT from "./DEADLEFT.json";
import FURASLEEPLOOP from "./FURASLEEPLOOP.json";
import NEUTRALSPECIALAIR from "./NEUTRALSPECIALAIR.json";
import TECHF from "./TECHF.json";
import WALK from "./WALK.json";
import CATCHCUT from "./CATCHCUT.json";
import DEADRIGHT from "./DEADRIGHT.json";
import FURASLEEPSTART from "./FURASLEEPSTART.json";
import NEUTRALSPECIALGROUND from "./NEUTRALSPECIALGROUND.json";
import TECHN from "./TECHN.json";
import WALKFAST from "./WALKFAST.json";
import CATCHWAIT from "./CATCHWAIT.json";
import DEADUP from "./DEADUP.json";
import GRAB from "./GRAB.json";
import NEUTRALSPECIALGROUNDTURN from "./NEUTRALSPECIALGROUNDTURN.json";
import TECHU from "./TECHU.json";
import WALKMIDDLE from "./WALKMIDDLE.json";
import CLIFFATTACKQUICK from "./CLIFFATTACKQUICK.json";
import DOWNATTACK from "./DOWNATTACK.json";
import GUARD from "./GUARD.json";
import OTTOTTO from "./OTTOTTO.json";
import THROWBACK from "./THROWBACK.json";
import WALKSLOW from "./WALKSLOW.json";
import CLIFFATTACKSLOW from "./CLIFFATTACKSLOW.json";
import DOWNBOUND from "./DOWNBOUND.json";
import GUARDOFF from "./GUARDOFF.json";
import OTTOTTOWAIT from "./OTTOTTOWAIT.json";
import THROWDOWN from "./THROWDOWN.json";
import WALLDAMAGE from "./WALLDAMAGE.json";
import CLIFFCATCH from "./CLIFFCATCH.json";
import DOWNDAMAGE from "./DOWNDAMAGE.json";
import GUARDON from "./GUARDON.json";
import PASS from "./PASS.json";
import THROWFORWARD from "./THROWFORWARD.json";
import WALLTECH from "./WALLTECH.json";
import CLIFFESCAPEQUICK from "./CLIFFESCAPEQUICK.json";
import DOWNSMASH from "./DOWNSMASH.json";
import JAB1 from "./JAB1.json";
import REBIRTH from "./REBIRTH.json";
import THROWNFOXBACK from "./THROWNFOXBACK.json";
import WALLTECHJUMP from "./WALLTECHJUMP.json";
import CLIFFESCAPESLOW from "./CLIFFESCAPESLOW.json";
import DOWNSPECIALAIR from "./DOWNSPECIALAIR.json";
import JAB2 from "./JAB2.json";
import REBIRTHWAIT from "./REBIRTHWAIT.json";
import THROWNFOXDOWN from "./THROWNFOXDOWN.json";
import CLIFFGETUPQUICK from "./CLIFFGETUPQUICK.json";
import DOWNSPECIALGROUND from "./DOWNSPECIALGROUND.json";
import JUMPAERIAL1 from "./JUMPAERIAL1.json";
import RUN from "./RUN.json";
import THROWNFOXFORWARD from "./THROWNFOXFORWARD.json";
import FURAFURA from "./FURAFURA.json";
import REBOUND from "./REBOUND.json";
import THROWNFALCOBACK from "./THROWNFALCOBACK.json";
import THROWNFALCODOWN from "./THROWNFALCODOWN.json";
import THROWNFALCOFORWARD from "./THROWNFALCOFORWARD.json";
import THROWNFALCOUP from "./THROWNFALCOUP.json";
import THROWNFALCONBACK from "./THROWNFALCONBACK.json";
import THROWNFALCONDOWN from "./THROWNFALCONDOWN.json";
import THROWNFALCONFORWARD from "./THROWNFALCONFORWARD.json";
import THROWNFALCONUP from "./THROWNFALCONUP.json";
import APPEAL from "./APPEAL.json";
import THROWNFALCONDIVE from "./THROWNFALCONDIVE.json";

export default {
  AERIALTURN1: AERIALTURN1,
  CLIFFGETUPSLOW: CLIFFGETUPSLOW,
  DOWNSTANDB: DOWNSTANDB,
  JUMPAERIAL2: JUMPAERIAL2,
  RUNBRAKE: RUNBRAKE,
  THROWNFOXUP: THROWNFOXUP,
  AERIALTURN2: AERIALTURN2,
  CLIFFJUMPQUICK: CLIFFJUMPQUICK,
  DOWNSTANDF: DOWNSTANDF,
  JUMPAERIAL3: JUMPAERIAL3,
  RUNTURN: RUNTURN,
  THROWNMARTHBACK: THROWNMARTHBACK,
  AERIALTURN3: AERIALTURN3,
  CLIFFJUMPSLOW: CLIFFJUMPSLOW,
  DOWNSTANDN: DOWNSTANDN,
  JUMPAERIAL4: JUMPAERIAL4,
  SHIELDBREAKDOWNBOUND: SHIELDBREAKDOWNBOUND,
  THROWNMARTHDOWN: THROWNMARTHDOWN,
  AERIALTURN4: AERIALTURN4,
  CLIFFWAIT: CLIFFWAIT,
  DOWNTILT: DOWNTILT,
  JUMPAERIAL5: JUMPAERIAL5,
  SHIELDBREAKFALL: SHIELDBREAKFALL,
  THROWNMARTHFORWARD: THROWNMARTHFORWARD,
  AERIALTURN5: AERIALTURN5,
  DAMAGEFALL: DAMAGEFALL,
  DOWNWAIT: DOWNWAIT,
  JUMPB: JUMPB,
  SHIELDBREAKFLY: SHIELDBREAKFLY,
  THROWNMARTHUP: THROWNMARTHUP,
  ATTACKAIRB: ATTACKAIRB,
  DAMAGEFLYHI: DAMAGEFLYHI,
  ENTRANCE: ENTRANCE,
  JUMPF: JUMPF,
  SHIELDBREAKSTAND: SHIELDBREAKSTAND,
  THROWNPUFFBACK: THROWNPUFFBACK,
  ATTACKAIRD: ATTACKAIRD,
  DAMAGEFLYLW: DAMAGEFLYLW,
  ESCAPEAIR: ESCAPEAIR,
  KNEEBEND: KNEEBEND,
  SIDESPECIALAIR: SIDESPECIALAIR,
  THROWNPUFFDOWN: THROWNPUFFDOWN,
  ATTACKAIRF: ATTACKAIRF,
  DAMAGEFLYN: DAMAGEFLYN,
  ESCAPEB: ESCAPEB,
  LANDING: LANDING,
  SIDESPECIALGROUND: SIDESPECIALGROUND,
  THROWNPUFFFORWARD: THROWNPUFFFORWARD,
  ATTACKAIRN: ATTACKAIRN,
  DAMAGEFLYTOP: DAMAGEFLYTOP,
  ESCAPEF: ESCAPEF,
  LANDINGATTACKAIRB: LANDINGATTACKAIRB,
  SLEEP: SLEEP,
  THROWNPUFFUP: THROWNPUFFUP,
  ATTACKAIRU: ATTACKAIRU,
  DAMAGEHI1: DAMAGEHI1,
  ESCAPEN: ESCAPEN,
  LANDINGATTACKAIRD: LANDINGATTACKAIRD,
  SMASHTURN: SMASHTURN,
  THROWUP: THROWUP,
  ATTACKDASH: ATTACKDASH,
  DAMAGEHI2: DAMAGEHI2,
  FALL: FALL,
  LANDINGATTACKAIRF: LANDINGATTACKAIRF,
  SQUAT: SQUAT,
  TILTTURN: TILTTURN,
  CAPTURECUT: CAPTURECUT,
  DAMAGEHI3: DAMAGEHI3,
  FALLSPECIAL: FALLSPECIAL,
  LANDINGATTACKAIRN: LANDINGATTACKAIRN,
  SQUATRV: SQUATRV,
  UPSMASH: UPSMASH,
  CAPTUREDAMAGE: CAPTUREDAMAGE,
  DAMAGEN2: DAMAGEN2,
  FORWARDSMASH: FORWARDSMASH,
  LANDINGATTACKAIRU: LANDINGATTACKAIRU,
  SQUATWAIT: SQUATWAIT,
  UPSPECIAL: UPSPECIAL,
  CAPTUREPULLED: CAPTUREPULLED,
  DASH: DASH,
  FORWARDTILT: FORWARDTILT,
  LANDINGFALLSPECIAL: LANDINGFALLSPECIAL,
  STOPCEIL: STOPCEIL,
  UPTILT: UPTILT,
  CAPTUREWAIT: CAPTUREWAIT,
  DEADDOWN: DEADDOWN,
  FURASLEEPEND: FURASLEEPEND,
  MISSFOOT: MISSFOOT,
  TECHB: TECHB,
  WAIT: WAIT,
  CATCHATTACK: CATCHATTACK,
  DEADLEFT: DEADLEFT,
  FURASLEEPLOOP: FURASLEEPLOOP,
  NEUTRALSPECIALAIR: NEUTRALSPECIALAIR,
  TECHF: TECHF,
  WALK: WALK,
  CATCHCUT: CATCHCUT,
  DEADRIGHT: DEADRIGHT,
  FURASLEEPSTART: FURASLEEPSTART,
  NEUTRALSPECIALGROUND: NEUTRALSPECIALGROUND,
  TECHN: TECHN,
  WALKFAST: WALKFAST,
  CATCHWAIT: CATCHWAIT,
  DEADUP: DEADUP,
  GRAB: GRAB,
  NEUTRALSPECIALGROUNDTURN: NEUTRALSPECIALGROUNDTURN,
  TECHU: TECHU,
  WALKMIDDLE: WALKMIDDLE,
  CLIFFATTACKQUICK: CLIFFATTACKQUICK,
  DOWNATTACK: DOWNATTACK,
  GUARD: GUARD,
  OTTOTTO: OTTOTTO,
  THROWBACK: THROWBACK,
  WALKSLOW: WALKSLOW,
  CLIFFATTACKSLOW: CLIFFATTACKSLOW,
  DOWNBOUND: DOWNBOUND,
  GUARDOFF: GUARDOFF,
  OTTOTTOWAIT: OTTOTTOWAIT,
  THROWDOWN: THROWDOWN,
  WALLDAMAGE: WALLDAMAGE,
  CLIFFCATCH: CLIFFCATCH,
  DOWNDAMAGE: DOWNDAMAGE,
  GUARDON: GUARDON,
  PASS: PASS,
  THROWFORWARD: THROWFORWARD,
  WALLTECH: WALLTECH,
  CLIFFESCAPEQUICK: CLIFFESCAPEQUICK,
  DOWNSMASH: DOWNSMASH,
  JAB1: JAB1,
  REBIRTH: REBIRTH,
  THROWNFOXBACK: THROWNFOXBACK,
  WALLTECHJUMP: WALLTECHJUMP,
  CLIFFESCAPESLOW: CLIFFESCAPESLOW,
  DOWNSPECIALAIR: DOWNSPECIALAIR,
  JAB2: JAB2,
  REBIRTHWAIT: REBIRTHWAIT,
  THROWNFOXDOWN: THROWNFOXDOWN,
  CLIFFGETUPQUICK: CLIFFGETUPQUICK,
  DOWNSPECIALGROUND: DOWNSPECIALGROUND,
  JUMPAERIAL1: JUMPAERIAL1,
  RUN: RUN,
  THROWNFOXFORWARD: THROWNFOXFORWARD,
  FURAFURA: FURAFURA,
  REBOUND: REBOUND,
  THROWNFALCOBACK: THROWNFALCOBACK,
  THROWNFALCODOWN: THROWNFALCODOWN,
  THROWNFALCOFORWARD: THROWNFALCOFORWARD,
  THROWNFALCOUP: THROWNFALCOUP,
  THROWNFALCONBACK: THROWNFALCONBACK,
  THROWNFALCONDOWN: THROWNFALCONDOWN,
  THROWNFALCONFORWARD: THROWNFALCONFORWARD,
  THROWNFALCONUP: THROWNFALCONUP,
  APPEAL: APPEAL,
  THROWNFALCONDIVE: THROWNFALCONDIVE,
};
