/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 battlefield.glb --types 
*/
import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.SkinnedMesh;
    mesh_1: THREE.SkinnedMesh;
    mesh_2: THREE.SkinnedMesh;
    mesh_3: THREE.SkinnedMesh;
    mesh_4: THREE.SkinnedMesh;
    mesh_5: THREE.SkinnedMesh;
    mesh_6: THREE.SkinnedMesh;
    mesh_7: THREE.SkinnedMesh;
    mesh_8: THREE.SkinnedMesh;
    mesh_9: THREE.SkinnedMesh;
    mesh_10: THREE.SkinnedMesh;
    mesh_11: THREE.SkinnedMesh;
    mesh_12: THREE.SkinnedMesh;
    mesh_13: THREE.SkinnedMesh;
    mesh_14: THREE.SkinnedMesh;
    mesh_15: THREE.SkinnedMesh;
    mesh_16: THREE.SkinnedMesh;
    mesh_17: THREE.SkinnedMesh;
    mesh_18: THREE.SkinnedMesh;
    mesh_19: THREE.SkinnedMesh;
    mesh_20: THREE.SkinnedMesh;
    mesh_21: THREE.SkinnedMesh;
    JOBJ_0: THREE.Bone;
    neutral_bone: THREE.Bone;
  };
  materials: {
    PaletteMaterial001: THREE.MeshBasicMaterial;
    Joint_12_Object_0_Material_0: THREE.MeshBasicMaterial;
    Joint_12_Object_10_Material_10: THREE.MeshBasicMaterial;
    Joint_12_Object_11_Material_11: THREE.MeshBasicMaterial;
    Joint_12_Object_18_Material_18: THREE.MeshBasicMaterial;
    Joint_12_Object_1_Material_1: THREE.MeshBasicMaterial;
    Joint_12_Object_20_Material_20: THREE.MeshBasicMaterial;
    Joint_12_Object_21_Material_21: THREE.MeshBasicMaterial;
    Joint_12_Object_3_Material_3: THREE.MeshBasicMaterial;
    Joint_12_Object_4_Material_4: THREE.MeshBasicMaterial;
    Joint_12_Object_5_Material_5: THREE.MeshBasicMaterial;
    Joint_12_Object_6_Material_6: THREE.MeshBasicMaterial;
    Joint_12_Object_7_Material_7: THREE.MeshBasicMaterial;
    Joint_12_Object_9_Material_9: THREE.MeshBasicMaterial;
  };
  animations: GLTFAction[];
};
interface GLTFAction extends THREE.AnimationClip {
  name: never;
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<
    JSX.IntrinsicElements["skinnedMesh"] | JSX.IntrinsicElements["bone"]
  >
>;

export function Battlefield(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/battlefield.glb") as GLTFResult;
  return (
    <group {...props} scale={0.8} rotation={[0, Math.PI, 0]} dispose={null}>
      <primitive object={nodes.JOBJ_0} />
      <primitive object={nodes.neutral_bone} />
      <skinnedMesh
        geometry={nodes.mesh_0.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.mesh_0.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_1.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.mesh_1.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_2.geometry}
        material={materials.Joint_12_Object_0_Material_0}
        skeleton={nodes.mesh_2.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_3.geometry}
        material={materials.Joint_12_Object_10_Material_10}
        skeleton={nodes.mesh_3.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_4.geometry}
        material={materials.Joint_12_Object_11_Material_11}
        skeleton={nodes.mesh_4.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_5.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.mesh_5.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_6.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.mesh_6.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_7.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.mesh_7.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_8.geometry}
        material={materials.Joint_12_Object_18_Material_18}
        skeleton={nodes.mesh_8.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_9.geometry}
        material={materials.Joint_12_Object_1_Material_1}
        skeleton={nodes.mesh_9.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_10.geometry}
        material={materials.Joint_12_Object_20_Material_20}
        skeleton={nodes.mesh_10.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_11.geometry}
        material={materials.Joint_12_Object_21_Material_21}
        skeleton={nodes.mesh_11.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_12.geometry}
        material={materials.Joint_12_Object_3_Material_3}
        skeleton={nodes.mesh_12.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_13.geometry}
        material={materials.Joint_12_Object_4_Material_4}
        skeleton={nodes.mesh_13.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_14.geometry}
        material={materials.Joint_12_Object_5_Material_5}
        skeleton={nodes.mesh_14.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_15.geometry}
        material={materials.Joint_12_Object_6_Material_6}
        skeleton={nodes.mesh_15.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_16.geometry}
        material={materials.Joint_12_Object_7_Material_7}
        skeleton={nodes.mesh_16.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_17.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.mesh_17.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_18.geometry}
        material={materials.Joint_12_Object_9_Material_9}
        skeleton={nodes.mesh_18.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_19.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.mesh_19.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_20.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.mesh_20.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.mesh_21.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.mesh_21.skeleton}
        position={[-36.5, -50, -85.5]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/battlefield.glb");
