/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dreamland.glb --types 
*/
import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.SkinnedMesh;
    mesh_1: THREE.SkinnedMesh;
    mesh_2: THREE.SkinnedMesh;
    mesh_3: THREE.SkinnedMesh;
    mesh_4: THREE.SkinnedMesh;
    mesh_5: THREE.SkinnedMesh;
    mesh_6: THREE.SkinnedMesh;
    mesh_7: THREE.SkinnedMesh;
    mesh_8: THREE.SkinnedMesh;
    JOBJ_0: THREE.Bone;
  };
  materials: {
    ["Joint_12_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_12_Object_1_Material_1.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_1_Object_1_Material_1.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_2_Object_2_Material_2.001"]: THREE.MeshBasicMaterial;
    ["Joint_6_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_7_Object_0_Material_0.001"]: THREE.MeshBasicMaterial;
    ["Joint_7_Object_1_Material_1.001"]: THREE.MeshBasicMaterial;
  };
  animations: GLTFAction[];
};
interface GLTFAction extends THREE.AnimationClip {
  name: never;
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<
    JSX.IntrinsicElements["skinnedMesh"] | JSX.IntrinsicElements["bone"]
  >
>;

export function Dreamland(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/dreamland.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.JOBJ_0} />
      <skinnedMesh
        geometry={nodes.mesh_0.geometry}
        material={materials["Joint_12_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_0.skeleton}
        position={[-77.281, -35.797, -8.359]}
        scale={0.009}
      />
      <skinnedMesh
        geometry={nodes.mesh_1.geometry}
        material={materials["Joint_12_Object_1_Material_1.001"]}
        skeleton={nodes.mesh_1.skeleton}
        position={[-77.281, -35.797, -8.359]}
        scale={0.009}
      />
      <skinnedMesh
        geometry={nodes.mesh_2.geometry}
        material={materials["Joint_1_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_2.skeleton}
        position={[-77.281, -35.797, -8.359]}
        scale={0.009}
      />
      <skinnedMesh
        geometry={nodes.mesh_3.geometry}
        material={materials["Joint_1_Object_1_Material_1.001"]}
        skeleton={nodes.mesh_3.skeleton}
        position={[-77.281, -35.797, -8.359]}
        scale={0.009}
      />
      <skinnedMesh
        geometry={nodes.mesh_4.geometry}
        material={materials["Joint_2_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_4.skeleton}
        position={[-77.281, -35.797, -8.359]}
        scale={0.009}
      />
      <skinnedMesh
        geometry={nodes.mesh_5.geometry}
        material={materials["Joint_2_Object_2_Material_2.001"]}
        skeleton={nodes.mesh_5.skeleton}
        position={[-77.281, -35.797, -8.359]}
        scale={0.009}
      />
      <skinnedMesh
        geometry={nodes.mesh_6.geometry}
        material={materials["Joint_6_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_6.skeleton}
        position={[-77.281, -35.797, -8.359]}
        scale={0.009}
      />
      <skinnedMesh
        geometry={nodes.mesh_7.geometry}
        material={materials["Joint_7_Object_0_Material_0.001"]}
        skeleton={nodes.mesh_7.skeleton}
        position={[-77.281, -35.797, -8.359]}
        scale={0.009}
      />
      <skinnedMesh
        geometry={nodes.mesh_8.geometry}
        material={materials["Joint_7_Object_1_Material_1.001"]}
        skeleton={nodes.mesh_8.skeleton}
        position={[-77.281, -35.797, -8.359]}
        scale={0.009}
      />
    </group>
  );
}

useGLTF.preload("/dreamland.glb");
