/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 jigglypuff.glb --types 
*/
import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.SkinnedMesh;
    mesh_1: THREE.SkinnedMesh;
    mesh_2: THREE.SkinnedMesh;
    mesh_3: THREE.SkinnedMesh;
    mesh_4: THREE.SkinnedMesh;
    JOBJ_0: THREE.Bone;
  };
  materials: {
    ["Joint_0_Object_0_Material_0.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_1_Material_1.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_13_Material_13.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_2_Material_2.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_3_Material_3.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "AppealL"
  | "AppealR"
  | "Attack11"
  | "Attack12"
  | "AttackAirB"
  | "AttackAirF"
  | "AttackAirHi"
  | "AttackAirLw"
  | "AttackAirN"
  | "AttackDash"
  | "AttackHi3"
  | "AttackHi4"
  | "AttackLw3"
  | "AttackLw4"
  | "AttackS3Hi"
  | "AttackS3Lw"
  | "AttackS3S"
  | "AttackS4"
  | "CaptureCut"
  | "CaptureDamageHi"
  | "CaptureDamageLw"
  | "CaptureJump"
  | "CapturePulledHi"
  | "CapturePulledLw"
  | "CaptureWaitHi"
  | "CaptureWaitLw"
  | "Catch"
  | "CatchAttack"
  | "CatchCut"
  | "CatchDash"
  | "CatchWait"
  | "CliffAttackQuick"
  | "CliffAttackSlow"
  | "CliffCatch"
  | "CliffClimbQuick"
  | "CliffClimbSlow"
  | "CliffEscapeQuick"
  | "CliffEscapeSlow"
  | "CliffJumpQuick1"
  | "CliffJumpQuick2"
  | "CliffJumpSlow1"
  | "CliffJumpSlow2"
  | "CliffWait"
  | "DamageAir1"
  | "DamageAir2"
  | "DamageAir3"
  | "DamageFall"
  | "DamageFlyHi"
  | "DamageFlyLw"
  | "DamageFlyN"
  | "DamageFlyRoll"
  | "DamageFlyTop"
  | "DamageHi1"
  | "DamageHi2"
  | "DamageHi3"
  | "DamageLw1"
  | "DamageLw2"
  | "DamageLw3"
  | "DamageN1"
  | "DamageN2"
  | "DamageN3"
  | "Dash"
  | "DownAttackD"
  | "DownAttackU"
  | "DownBackD"
  | "DownBackU"
  | "DownBoundD"
  | "DownBoundU"
  | "DownDamageD"
  | "DownDamageU"
  | "DownFowardD"
  | "DownFowardU"
  | "DownSpotU"
  | "DownStandD"
  | "DownStandU"
  | "DownWaitD"
  | "DownWaitU"
  | "Entry"
  | "EscapeAir"
  | "EscapeB"
  | "EscapeF"
  | "EscapeN"
  | "Fall"
  | "FallAerial"
  | "FallAerialB"
  | "FallAerialF"
  | "FallB"
  | "FallF"
  | "FallSpecial"
  | "FallSpecialB"
  | "FallSpecialF"
  | "FuraFura"
  | "FuraSleepEnd"
  | "FuraSleepLoop"
  | "FuraSleepStart"
  | "Guard"
  | "GuardDamage"
  | "GuardOff"
  | "GuardOn"
  | "HeavyGet"
  | "HeavyThrowB"
  | "HeavyThrowF"
  | "HeavyThrowHi"
  | "HeavyThrowLw"
  | "HeavyWalk1"
  | "HeavyWalk2"
  | "ItemBlind"
  | "ItemHammerMove"
  | "ItemHammerWait"
  | "ItemParasolFall"
  | "ItemParasolOpen"
  | "ItemScopeAirEnd"
  | "ItemScopeAirFire"
  | "ItemScopeAirRapid"
  | "ItemScopeAirStart"
  | "ItemScopeEnd"
  | "ItemScopeFire"
  | "ItemScopeRapid"
  | "ItemScopeStart"
  | "ItemScrew"
  | "ItemScrewAir"
  | "ItemScrewDamage"
  | "ItemShoot"
  | "ItemShootAir"
  | "JumpAerialF1"
  | "JumpAerialF2"
  | "JumpAerialF3"
  | "JumpAerialF4"
  | "JumpAerialF5"
  | "JumpB"
  | "JumpF"
  | "Landing"
  | "LandingAirB"
  | "LandingAirF"
  | "LandingAirHi"
  | "LandingAirLw"
  | "LandingAirN"
  | "LightGet"
  | "LightThrowAirB"
  | "LightThrowAirF"
  | "LightThrowAirHi"
  | "LightThrowAirLw"
  | "LightThrowB"
  | "LightThrowDash"
  | "LightThrowDrop"
  | "LightThrowF"
  | "LightThrowHi"
  | "LightThrowLw"
  | "MissFoot"
  | "Ottotto"
  | "OttottoWait"
  | "Pass"
  | "Passive"
  | "PassiveCeil"
  | "PassiveStandB"
  | "PassiveStandF"
  | "PassiveWall"
  | "PassiveWallJump"
  | "Rebound"
  | "Run"
  | "RunBrake"
  | "SpecialAirHiL"
  | "SpecialAirHiR"
  | "SpecialAirLwL"
  | "SpecialAirLwR"
  | "SpecialAirNEndL"
  | "SpecialAirNEndR"
  | "SpecialAirNStartL"
  | "SpecialAirNStartR"
  | "SpecialAirS"
  | "SpecialHiL"
  | "SpecialHiR"
  | "SpecialLwL"
  | "SpecialLwR"
  | "SpecialN"
  | "SpecialNEndL"
  | "SpecialNEndR"
  | "SpecialNStartL"
  | "SpecialNStartR"
  | "SpecialS"
  | "Squat"
  | "SquatRv"
  | "SquatWait1"
  | "SquatWait2"
  | "SquatWaitItem"
  | "StopCeil"
  | "StopWall"
  | "Swing1"
  | "Swing3"
  | "Swing4"
  | "SwingDash"
  | "ThrowB"
  | "ThrowF"
  | "ThrowHi"
  | "ThrowLw"
  | "Turn"
  | "TurnRun"
  | "Wait"
  | "WaitItem"
  | "WalkFast"
  | "WalkMiddle"
  | "WalkSlow"
  | "WallDamage";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}
type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<
    JSX.IntrinsicElements["skinnedMesh"] | JSX.IntrinsicElements["bone"]
  >
>;

export function Jigglypuff(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/jigglypuff.glb",
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="jigglypuff">
        <group name="Armature">
          <group name="Joint_0_Object_0">
            <skinnedMesh
              name="mesh_0"
              geometry={nodes.mesh_0.geometry}
              material={materials["Joint_0_Object_0_Material_0.001"]}
              skeleton={nodes.mesh_0.skeleton}
              position={[-6.787, -0.022, -5.25]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_1">
            <skinnedMesh
              name="mesh_1"
              geometry={nodes.mesh_1.geometry}
              material={materials["Joint_0_Object_1_Material_1.001"]}
              skeleton={nodes.mesh_1.skeleton}
              position={[-6.787, -0.022, -5.25]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_13">
            <skinnedMesh
              name="mesh_2"
              geometry={nodes.mesh_2.geometry}
              material={materials["Joint_0_Object_13_Material_13.001"]}
              skeleton={nodes.mesh_2.skeleton}
              position={[-6.787, -0.022, -5.25]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_2">
            <skinnedMesh
              name="mesh_3"
              geometry={nodes.mesh_3.geometry}
              material={materials["Joint_0_Object_2_Material_2.001"]}
              skeleton={nodes.mesh_3.skeleton}
              position={[-6.787, -0.022, -5.25]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_3">
            <skinnedMesh
              name="mesh_4"
              geometry={nodes.mesh_4.geometry}
              material={materials["Joint_0_Object_3_Material_3.001"]}
              skeleton={nodes.mesh_4.skeleton}
              position={[-6.787, -0.022, -5.25]}
              scale={0.001}
            />
          </group>
          <primitive object={nodes.JOBJ_0} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/jigglypuff.glb");
