/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 marth.glb --types 
*/
import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.SkinnedMesh;
    mesh_1: THREE.SkinnedMesh;
    mesh_2: THREE.SkinnedMesh;
    mesh_3: THREE.SkinnedMesh;
    mesh_4: THREE.SkinnedMesh;
    mesh_5: THREE.SkinnedMesh;
    mesh_6: THREE.SkinnedMesh;
    mesh_7: THREE.SkinnedMesh;
    mesh_8: THREE.SkinnedMesh;
    mesh_9: THREE.SkinnedMesh;
    mesh_10: THREE.SkinnedMesh;
    mesh_11: THREE.SkinnedMesh;
    mesh_12: THREE.SkinnedMesh;
    mesh_13: THREE.SkinnedMesh;
    mesh_14: THREE.SkinnedMesh;
    mesh_15: THREE.SkinnedMesh;
    mesh_16: THREE.SkinnedMesh;
    mesh_17: THREE.SkinnedMesh;
    mesh_18: THREE.SkinnedMesh;
    mesh_19: THREE.SkinnedMesh;
    mesh_20: THREE.SkinnedMesh;
    mesh_21: THREE.SkinnedMesh;
    mesh_22: THREE.SkinnedMesh;
    mesh_23: THREE.SkinnedMesh;
    mesh_24: THREE.SkinnedMesh;
    mesh_25: THREE.SkinnedMesh;
    mesh_26: THREE.SkinnedMesh;
    mesh_27: THREE.SkinnedMesh;
    mesh_28: THREE.SkinnedMesh;
    mesh_29: THREE.SkinnedMesh;
    mesh_30: THREE.SkinnedMesh;
    mesh_31: THREE.SkinnedMesh;
    mesh_32: THREE.SkinnedMesh;
    mesh_33: THREE.SkinnedMesh;
    mesh_34: THREE.SkinnedMesh;
    mesh_35: THREE.SkinnedMesh;
    mesh_36: THREE.SkinnedMesh;
    mesh_37: THREE.SkinnedMesh;
    mesh_38: THREE.SkinnedMesh;
    mesh_39: THREE.SkinnedMesh;
    mesh_40: THREE.SkinnedMesh;
    mesh_41: THREE.SkinnedMesh;
    mesh_42: THREE.SkinnedMesh;
    mesh_43: THREE.SkinnedMesh;
    mesh_44: THREE.SkinnedMesh;
    mesh_45: THREE.SkinnedMesh;
    mesh_46: THREE.SkinnedMesh;
    mesh_47: THREE.SkinnedMesh;
    JOBJ_0: THREE.Bone;
  };
  materials: {
    ["Joint_0_Object_0_Material_0.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_1_Material_1.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_10_Material_10.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_11_Material_11.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_12_Material_12.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_13_Material_13.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_14_Material_14.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_15_Material_15.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_16_Material_16.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_17_Material_17.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_18_Material_18.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_19_Material_19.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_2_Material_2.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_20_Material_20.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_21_Material_21.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_22_Material_22.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_23_Material_23.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_24_Material_24.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_25_Material_25.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_26_Material_26.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_28_Material_28.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_29_Material_29.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_3_Material_3.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_31_Material_31.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_32_Material_32.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_33_Material_33.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_34_Material_34.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_35_Material_35.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_36_Material_36.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_37_Material_37.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_38_Material_38.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_4_Material_4.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_5_Material_5.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_6_Material_6.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_61_Material_61.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_62_Material_62.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_7_Material_7.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_8_Material_8.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_9_Material_9.001"]: THREE.MeshStandardMaterial;
    ["Joint_19_Object_10_Material_10.001"]: THREE.MeshStandardMaterial;
    ["Joint_19_Object_11_Material_11.001"]: THREE.MeshStandardMaterial;
    ["Joint_19_Object_6_Material_6.001"]: THREE.MeshStandardMaterial;
    ["Joint_19_Object_7_Material_7.001"]: THREE.MeshStandardMaterial;
    ["Joint_19_Object_8_Material_8.001"]: THREE.MeshStandardMaterial;
    ["Joint_19_Object_9_Material_9.001"]: THREE.MeshStandardMaterial;
    ["Joint_60_Object_0_Material_0.001"]: THREE.MeshStandardMaterial;
    ["Joint_60_Object_1_Material_1.001"]: THREE.MeshStandardMaterial;
    ["Joint_76_Object_0_Material_0.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "Appeal"
  | "Attack11"
  | "Attack12"
  | "AttackAirB"
  | "AttackAirF"
  | "AttackAirHi"
  | "AttackAirLw"
  | "AttackAirN"
  | "AttackDash"
  | "AttackHi3"
  | "AttackHi4"
  | "AttackLw3"
  | "AttackLw4"
  | "AttackS31"
  | "AttackS4"
  | "CaptureCut"
  | "CaptureDamageHi"
  | "CaptureDamageLw"
  | "CaptureJump"
  | "CapturePulledHi"
  | "CapturePulledLw"
  | "CaptureWaitHi"
  | "CaptureWaitLw"
  | "Catch"
  | "CatchAttack"
  | "CatchCut"
  | "CatchDash"
  | "CatchWait"
  | "CliffAttackQuick"
  | "CliffAttackSlow"
  | "CliffCatch"
  | "CliffClimbQuick"
  | "CliffClimbSlow"
  | "CliffEscapeQuick"
  | "CliffEscapeSlow"
  | "CliffJumpQuick1"
  | "CliffJumpQuick2"
  | "CliffJumpSlow1"
  | "CliffJumpSlow2"
  | "CliffWait"
  | "DamageAir1"
  | "DamageAir2"
  | "DamageAir3"
  | "DamageFall"
  | "DamageFlyHi"
  | "DamageFlyLw"
  | "DamageFlyN"
  | "DamageFlyRoll"
  | "DamageFlyTop"
  | "DamageHi1"
  | "DamageHi2"
  | "DamageHi3"
  | "DamageLw1"
  | "DamageLw2"
  | "DamageLw3"
  | "DamageN1"
  | "DamageN2"
  | "DamageN3"
  | "Dash"
  | "DownAttackD"
  | "DownAttackU"
  | "DownBackD"
  | "DownBackU"
  | "DownBoundD"
  | "DownBoundU"
  | "DownDamageD"
  | "DownDamageU"
  | "DownFowardD"
  | "DownFowardU"
  | "DownSpotU"
  | "DownStandD"
  | "DownStandU"
  | "DownWaitD"
  | "DownWaitU"
  | "Entry"
  | "EscapeAir"
  | "EscapeB"
  | "EscapeF"
  | "EscapeN"
  | "Fall"
  | "FallAerial"
  | "FallAerialB"
  | "FallAerialF"
  | "FallB"
  | "FallF"
  | "FallSpecial"
  | "FallSpecialB"
  | "FallSpecialF"
  | "FuraFura"
  | "FuraSleepEnd"
  | "FuraSleepLoop"
  | "FuraSleepStart"
  | "Guard"
  | "GuardDamage"
  | "GuardOff"
  | "GuardOn"
  | "HeavyGet"
  | "HeavyThrowB"
  | "HeavyThrowF"
  | "HeavyThrowHi"
  | "HeavyThrowLw"
  | "HeavyWalk1"
  | "HeavyWalk2"
  | "ItemBlind"
  | "ItemHammerMove"
  | "ItemHammerWait"
  | "ItemParasolFall"
  | "ItemParasolOpen"
  | "ItemScopeAirEnd"
  | "ItemScopeAirFire"
  | "ItemScopeAirRapid"
  | "ItemScopeAirStart"
  | "ItemScopeEnd"
  | "ItemScopeFire"
  | "ItemScopeRapid"
  | "ItemScopeStart"
  | "ItemScrew"
  | "ItemScrewAir"
  | "ItemScrewDamage"
  | "ItemShoot"
  | "ItemShootAir"
  | "JumpAerialB"
  | "JumpAerialF"
  | "JumpB"
  | "JumpF"
  | "Landing"
  | "LandingAirB"
  | "LandingAirF"
  | "LandingAirHi"
  | "LandingAirLw"
  | "LandingAirN"
  | "LightGet"
  | "LightThrowAirB"
  | "LightThrowAirF"
  | "LightThrowAirHi"
  | "LightThrowAirLw"
  | "LightThrowB"
  | "LightThrowDash"
  | "LightThrowDrop"
  | "LightThrowF"
  | "LightThrowHi"
  | "LightThrowLw"
  | "MissFoot"
  | "Ottotto"
  | "OttottoWait"
  | "Pass"
  | "Passive"
  | "PassiveCeil"
  | "PassiveStandB"
  | "PassiveStandF"
  | "PassiveWall"
  | "PassiveWallJump"
  | "Rebound"
  | "Run"
  | "RunBrake"
  | "SpecialAirHi"
  | "SpecialAirLw"
  | "SpecialAirLwHit"
  | "SpecialAirNEnd"
  | "SpecialAirNLoop"
  | "SpecialAirNStart"
  | "SpecialAirS1"
  | "SpecialAirS2Hi"
  | "SpecialAirS2Lw"
  | "SpecialAirS3Hi"
  | "SpecialAirS3Lw"
  | "SpecialAirS3S"
  | "SpecialAirS4Hi"
  | "SpecialAirS4Lw"
  | "SpecialAirS4S"
  | "SpecialHi"
  | "SpecialLw"
  | "SpecialLwHit"
  | "SpecialNEnd"
  | "SpecialNLoop"
  | "SpecialNStart"
  | "SpecialS1"
  | "SpecialS2Hi"
  | "SpecialS2Lw"
  | "SpecialS3Hi"
  | "SpecialS3Lw"
  | "SpecialS3S"
  | "SpecialS4Hi"
  | "SpecialS4Lw"
  | "SpecialS4S"
  | "Squat"
  | "SquatRv"
  | "SquatWait"
  | "SquatWaitItem"
  | "StopCeil"
  | "StopWall"
  | "Swing1"
  | "Swing3"
  | "Swing4"
  | "SwingDash"
  | "ThrowB"
  | "ThrowF"
  | "ThrowHi"
  | "ThrowLw"
  | "Turn"
  | "TurnRun"
  | "Wait1"
  | "Wait2"
  | "WaitItem"
  | "WalkFast"
  | "WalkMiddle"
  | "WalkSlow"
  | "WallDamage";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}
type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<
    JSX.IntrinsicElements["skinnedMesh"] | JSX.IntrinsicElements["bone"]
  >
>;

export function Marth(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/marth.glb",
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.Wait1?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} scale={1.15} dispose={null}>
      <group name="marth">
        <group name="Armature">
          <group name="Joint_0_Object_0">
            <skinnedMesh
              name="mesh_0"
              geometry={nodes.mesh_0.geometry}
              material={materials["Joint_0_Object_0_Material_0.001"]}
              skeleton={nodes.mesh_0.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_1">
            <skinnedMesh
              name="mesh_1"
              geometry={nodes.mesh_1.geometry}
              material={materials["Joint_0_Object_1_Material_1.001"]}
              skeleton={nodes.mesh_1.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_10">
            <skinnedMesh
              name="mesh_2"
              geometry={nodes.mesh_2.geometry}
              material={materials["Joint_0_Object_10_Material_10.001"]}
              skeleton={nodes.mesh_2.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_11">
            <skinnedMesh
              name="mesh_3"
              geometry={nodes.mesh_3.geometry}
              material={materials["Joint_0_Object_11_Material_11.001"]}
              skeleton={nodes.mesh_3.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_12">
            <skinnedMesh
              name="mesh_4"
              geometry={nodes.mesh_4.geometry}
              material={materials["Joint_0_Object_12_Material_12.001"]}
              skeleton={nodes.mesh_4.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_13">
            <skinnedMesh
              name="mesh_5"
              geometry={nodes.mesh_5.geometry}
              material={materials["Joint_0_Object_13_Material_13.001"]}
              skeleton={nodes.mesh_5.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_14">
            <skinnedMesh
              name="mesh_6"
              geometry={nodes.mesh_6.geometry}
              material={materials["Joint_0_Object_14_Material_14.001"]}
              skeleton={nodes.mesh_6.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_15">
            <skinnedMesh
              name="mesh_7"
              geometry={nodes.mesh_7.geometry}
              material={materials["Joint_0_Object_15_Material_15.001"]}
              skeleton={nodes.mesh_7.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_16">
            <skinnedMesh
              name="mesh_8"
              geometry={nodes.mesh_8.geometry}
              material={materials["Joint_0_Object_16_Material_16.001"]}
              skeleton={nodes.mesh_8.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_17">
            <skinnedMesh
              name="mesh_9"
              geometry={nodes.mesh_9.geometry}
              material={materials["Joint_0_Object_17_Material_17.001"]}
              skeleton={nodes.mesh_9.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_18">
            <skinnedMesh
              name="mesh_10"
              geometry={nodes.mesh_10.geometry}
              material={materials["Joint_0_Object_18_Material_18.001"]}
              skeleton={nodes.mesh_10.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_19">
            <skinnedMesh
              name="mesh_11"
              geometry={nodes.mesh_11.geometry}
              material={materials["Joint_0_Object_19_Material_19.001"]}
              skeleton={nodes.mesh_11.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_2">
            <skinnedMesh
              name="mesh_12"
              geometry={nodes.mesh_12.geometry}
              material={materials["Joint_0_Object_2_Material_2.001"]}
              skeleton={nodes.mesh_12.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_20">
            <skinnedMesh
              name="mesh_13"
              geometry={nodes.mesh_13.geometry}
              material={materials["Joint_0_Object_20_Material_20.001"]}
              skeleton={nodes.mesh_13.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_21">
            <skinnedMesh
              name="mesh_14"
              geometry={nodes.mesh_14.geometry}
              material={materials["Joint_0_Object_21_Material_21.001"]}
              skeleton={nodes.mesh_14.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_22">
            <skinnedMesh
              name="mesh_15"
              geometry={nodes.mesh_15.geometry}
              material={materials["Joint_0_Object_22_Material_22.001"]}
              skeleton={nodes.mesh_15.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_23">
            <skinnedMesh
              name="mesh_16"
              geometry={nodes.mesh_16.geometry}
              material={materials["Joint_0_Object_23_Material_23.001"]}
              skeleton={nodes.mesh_16.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_24">
            <skinnedMesh
              name="mesh_17"
              geometry={nodes.mesh_17.geometry}
              material={materials["Joint_0_Object_24_Material_24.001"]}
              skeleton={nodes.mesh_17.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_25">
            <skinnedMesh
              name="mesh_18"
              geometry={nodes.mesh_18.geometry}
              material={materials["Joint_0_Object_25_Material_25.001"]}
              skeleton={nodes.mesh_18.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_26">
            <skinnedMesh
              name="mesh_19"
              geometry={nodes.mesh_19.geometry}
              material={materials["Joint_0_Object_26_Material_26.001"]}
              skeleton={nodes.mesh_19.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_28">
            <skinnedMesh
              name="mesh_20"
              geometry={nodes.mesh_20.geometry}
              material={materials["Joint_0_Object_28_Material_28.001"]}
              skeleton={nodes.mesh_20.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_29">
            <skinnedMesh
              name="mesh_21"
              geometry={nodes.mesh_21.geometry}
              material={materials["Joint_0_Object_29_Material_29.001"]}
              skeleton={nodes.mesh_21.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_3">
            <skinnedMesh
              name="mesh_22"
              geometry={nodes.mesh_22.geometry}
              material={materials["Joint_0_Object_3_Material_3.001"]}
              skeleton={nodes.mesh_22.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_31">
            <skinnedMesh
              name="mesh_23"
              geometry={nodes.mesh_23.geometry}
              material={materials["Joint_0_Object_31_Material_31.001"]}
              skeleton={nodes.mesh_23.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_32">
            <skinnedMesh
              name="mesh_24"
              geometry={nodes.mesh_24.geometry}
              material={materials["Joint_0_Object_32_Material_32.001"]}
              skeleton={nodes.mesh_24.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_33">
            <skinnedMesh
              name="mesh_25"
              geometry={nodes.mesh_25.geometry}
              material={materials["Joint_0_Object_33_Material_33.001"]}
              skeleton={nodes.mesh_25.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_34">
            <skinnedMesh
              name="mesh_26"
              geometry={nodes.mesh_26.geometry}
              material={materials["Joint_0_Object_34_Material_34.001"]}
              skeleton={nodes.mesh_26.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_35">
            <skinnedMesh
              name="mesh_27"
              geometry={nodes.mesh_27.geometry}
              material={materials["Joint_0_Object_35_Material_35.001"]}
              skeleton={nodes.mesh_27.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_36">
            <skinnedMesh
              name="mesh_28"
              geometry={nodes.mesh_28.geometry}
              material={materials["Joint_0_Object_36_Material_36.001"]}
              skeleton={nodes.mesh_28.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_37">
            <skinnedMesh
              name="mesh_29"
              geometry={nodes.mesh_29.geometry}
              material={materials["Joint_0_Object_37_Material_37.001"]}
              skeleton={nodes.mesh_29.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_38">
            <skinnedMesh
              name="mesh_30"
              geometry={nodes.mesh_30.geometry}
              material={materials["Joint_0_Object_38_Material_38.001"]}
              skeleton={nodes.mesh_30.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_4">
            <skinnedMesh
              name="mesh_31"
              geometry={nodes.mesh_31.geometry}
              material={materials["Joint_0_Object_4_Material_4.001"]}
              skeleton={nodes.mesh_31.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_5">
            <skinnedMesh
              name="mesh_32"
              geometry={nodes.mesh_32.geometry}
              material={materials["Joint_0_Object_5_Material_5.001"]}
              skeleton={nodes.mesh_32.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_6">
            <skinnedMesh
              name="mesh_33"
              geometry={nodes.mesh_33.geometry}
              material={materials["Joint_0_Object_6_Material_6.001"]}
              skeleton={nodes.mesh_33.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_61">
            <skinnedMesh
              name="mesh_34"
              geometry={nodes.mesh_34.geometry}
              material={materials["Joint_0_Object_61_Material_61.001"]}
              skeleton={nodes.mesh_34.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_62">
            <skinnedMesh
              name="mesh_35"
              geometry={nodes.mesh_35.geometry}
              material={materials["Joint_0_Object_62_Material_62.001"]}
              skeleton={nodes.mesh_35.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_7">
            <skinnedMesh
              name="mesh_36"
              geometry={nodes.mesh_36.geometry}
              material={materials["Joint_0_Object_7_Material_7.001"]}
              skeleton={nodes.mesh_36.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_8">
            <skinnedMesh
              name="mesh_37"
              geometry={nodes.mesh_37.geometry}
              material={materials["Joint_0_Object_8_Material_8.001"]}
              skeleton={nodes.mesh_37.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_9">
            <skinnedMesh
              name="mesh_38"
              geometry={nodes.mesh_38.geometry}
              material={materials["Joint_0_Object_9_Material_9.001"]}
              skeleton={nodes.mesh_38.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_19_Object_10_SINGLE">
            <skinnedMesh
              name="mesh_39"
              geometry={nodes.mesh_39.geometry}
              material={materials["Joint_19_Object_10_Material_10.001"]}
              skeleton={nodes.mesh_39.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_19_Object_11_SINGLE">
            <skinnedMesh
              name="mesh_40"
              geometry={nodes.mesh_40.geometry}
              material={materials["Joint_19_Object_11_Material_11.001"]}
              skeleton={nodes.mesh_40.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_19_Object_6_SINGLE">
            <skinnedMesh
              name="mesh_41"
              geometry={nodes.mesh_41.geometry}
              material={materials["Joint_19_Object_6_Material_6.001"]}
              skeleton={nodes.mesh_41.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_19_Object_7_SINGLE">
            <skinnedMesh
              name="mesh_42"
              geometry={nodes.mesh_42.geometry}
              material={materials["Joint_19_Object_7_Material_7.001"]}
              skeleton={nodes.mesh_42.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_19_Object_8_SINGLE">
            <skinnedMesh
              name="mesh_43"
              geometry={nodes.mesh_43.geometry}
              material={materials["Joint_19_Object_8_Material_8.001"]}
              skeleton={nodes.mesh_43.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_19_Object_9_SINGLE">
            <skinnedMesh
              name="mesh_44"
              geometry={nodes.mesh_44.geometry}
              material={materials["Joint_19_Object_9_Material_9.001"]}
              skeleton={nodes.mesh_44.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_60_Object_0_SINGLE">
            <skinnedMesh
              name="mesh_45"
              geometry={nodes.mesh_45.geometry}
              material={materials["Joint_60_Object_0_Material_0.001"]}
              skeleton={nodes.mesh_45.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_60_Object_1_SINGLE">
            <skinnedMesh
              name="mesh_46"
              geometry={nodes.mesh_46.geometry}
              material={materials["Joint_60_Object_1_Material_1.001"]}
              skeleton={nodes.mesh_46.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <group name="Joint_76_Object_0_SINGLE">
            <skinnedMesh
              name="mesh_47"
              geometry={nodes.mesh_47.geometry}
              material={materials["Joint_76_Object_0_Material_0.001"]}
              skeleton={nodes.mesh_47.skeleton}
              position={[-9.416, -0.005, -11.038]}
              scale={0.001}
            />
          </group>
          <primitive object={nodes.JOBJ_0} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/marth.glb");
