/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sheik.glb --types 
*/
import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.SkinnedMesh;
    mesh_1: THREE.SkinnedMesh;
    mesh_2: THREE.SkinnedMesh;
    mesh_3: THREE.SkinnedMesh;
    mesh_4: THREE.SkinnedMesh;
    mesh_5: THREE.SkinnedMesh;
    mesh_6: THREE.SkinnedMesh;
    mesh_7: THREE.SkinnedMesh;
    mesh_8: THREE.SkinnedMesh;
    mesh_9: THREE.SkinnedMesh;
    mesh_10: THREE.SkinnedMesh;
    mesh_11: THREE.SkinnedMesh;
    mesh_12: THREE.SkinnedMesh;
    mesh_13: THREE.SkinnedMesh;
    mesh_14: THREE.SkinnedMesh;
    mesh_15: THREE.SkinnedMesh;
    mesh_16: THREE.SkinnedMesh;
    mesh_17: THREE.SkinnedMesh;
    mesh_18: THREE.SkinnedMesh;
    mesh_19: THREE.SkinnedMesh;
    mesh_20: THREE.SkinnedMesh;
    mesh_21: THREE.SkinnedMesh;
    mesh_22: THREE.SkinnedMesh;
    JOBJ_0: THREE.Bone;
  };
  materials: {
    ["Joint_0_Object_0_Material_0.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_1_Material_1.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_10_Material_10.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_12_Material_12.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_14_Material_14.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_15_Material_15.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_16_Material_16.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_18_Material_18.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_19_Material_19.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_2_Material_2.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_20_Material_20.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_25_Material_25.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_26_Material_26.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_27_Material_27.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_28_Material_28.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_29_Material_29.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_3_Material_3.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_30_Material_30.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_36_Material_36.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_37_Material_37.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_38_Material_38.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_5_Material_5.001"]: THREE.MeshStandardMaterial;
    ["Joint_0_Object_7_Material_7.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName =
  | "Appeal"
  | "Attack100End"
  | "Attack100Loop"
  | "Attack100Start"
  | "Attack11"
  | "Attack12"
  | "AttackAirB"
  | "AttackAirF"
  | "AttackAirHi"
  | "AttackAirLw"
  | "AttackAirN"
  | "AttackDash"
  | "AttackHi3"
  | "AttackHi4"
  | "AttackLw3"
  | "AttackLw4"
  | "AttackS3"
  | "AttackS4"
  | "CaptureCut"
  | "CaptureDamageHi"
  | "CaptureDamageLw"
  | "CaptureJump"
  | "CapturePulledHi"
  | "CapturePulledLw"
  | "CaptureWaitHi"
  | "CaptureWaitLw"
  | "Catch"
  | "CatchAttack"
  | "CatchCut"
  | "CatchDash"
  | "CatchWait"
  | "CliffAttackQuick"
  | "CliffAttackSlow"
  | "CliffCatch"
  | "CliffClimbQuick"
  | "CliffClimbSlow"
  | "CliffEscapeQuick"
  | "CliffEscapeSlow"
  | "CliffJumpQuick1"
  | "CliffJumpQuick2"
  | "CliffJumpSlow1"
  | "CliffJumpSlow2"
  | "CliffWait"
  | "DamageAir1"
  | "DamageAir2"
  | "DamageAir3"
  | "DamageFall"
  | "DamageFlyHi"
  | "DamageFlyLw"
  | "DamageFlyN"
  | "DamageFlyRoll"
  | "DamageFlyTop"
  | "DamageHi1"
  | "DamageHi2"
  | "DamageHi3"
  | "DamageLw1"
  | "DamageLw2"
  | "DamageLw3"
  | "DamageN1"
  | "DamageN2"
  | "DamageN3"
  | "Dash"
  | "DownAttackD"
  | "DownAttackU"
  | "DownBackD"
  | "DownBackU"
  | "DownBoundD"
  | "DownBoundU"
  | "DownDamageD"
  | "DownDamageU"
  | "DownFowardD"
  | "DownFowardU"
  | "DownSpotU"
  | "DownStandD"
  | "DownStandU"
  | "DownWaitD"
  | "DownWaitU"
  | "Entry"
  | "EscapeAir"
  | "EscapeB"
  | "EscapeF"
  | "EscapeN"
  | "Fall"
  | "FallAerial"
  | "FallAerialB"
  | "FallAerialF"
  | "FallB"
  | "FallF"
  | "FallSpecial"
  | "FallSpecialB"
  | "FallSpecialF"
  | "FuraFura"
  | "FuraSleepEnd"
  | "FuraSleepLoop"
  | "FuraSleepStart"
  | "Guard"
  | "GuardDamage"
  | "GuardOff"
  | "GuardOn"
  | "HeavyGet"
  | "HeavyThrowB"
  | "HeavyThrowF"
  | "HeavyThrowHi"
  | "HeavyThrowLw"
  | "HeavyWalk1"
  | "HeavyWalk2"
  | "ItemBlind"
  | "ItemHammerMove"
  | "ItemHammerWait"
  | "ItemParasolFall"
  | "ItemParasolOpen"
  | "ItemScopeAirEnd"
  | "ItemScopeAirFire"
  | "ItemScopeAirRapid"
  | "ItemScopeAirStart"
  | "ItemScopeEnd"
  | "ItemScopeFire"
  | "ItemScopeRapid"
  | "ItemScopeStart"
  | "ItemScrew"
  | "ItemScrewAir"
  | "ItemScrewDamage"
  | "ItemShoot"
  | "ItemShootAir"
  | "JumpAerialB"
  | "JumpAerialF"
  | "JumpB"
  | "JumpF"
  | "Landing"
  | "LandingAirB"
  | "LandingAirF"
  | "LandingAirHi"
  | "LandingAirLw"
  | "LandingAirN"
  | "LightGet"
  | "LightThrowAirB"
  | "LightThrowAirF"
  | "LightThrowAirHi"
  | "LightThrowAirLw"
  | "LightThrowB"
  | "LightThrowDash"
  | "LightThrowDrop"
  | "LightThrowF"
  | "LightThrowHi"
  | "LightThrowLw"
  | "MissFoot"
  | "Ottotto"
  | "OttottoWait"
  | "Pass"
  | "Passive"
  | "PassiveCeil"
  | "PassiveStandB"
  | "PassiveStandF"
  | "PassiveWall"
  | "PassiveWallJump"
  | "Rebound"
  | "Run"
  | "RunBrake"
  | "SpecialAirHi"
  | "SpecialAirHiStart"
  | "SpecialAirLw"
  | "SpecialAirLw2"
  | "SpecialAirNCansel"
  | "SpecialAirNEnd"
  | "SpecialAirNLoop"
  | "SpecialAirNStart"
  | "SpecialAirS"
  | "SpecialAirSEnd"
  | "SpecialAirSStart"
  | "SpecialHi"
  | "SpecialHiStart"
  | "SpecialLw"
  | "SpecialLw2"
  | "SpecialNCansel"
  | "SpecialNEnd"
  | "SpecialNLoop"
  | "SpecialNStart"
  | "SpecialS"
  | "SpecialSEnd"
  | "SpecialSStart"
  | "Squat"
  | "SquatRv"
  | "SquatWait"
  | "SquatWaitItem"
  | "StopCeil"
  | "StopWall"
  | "Swing1"
  | "Swing3"
  | "Swing4"
  | "SwingDash"
  | "ThrowB"
  | "ThrowF"
  | "ThrowHi"
  | "ThrowLw"
  | "Turn"
  | "TurnRun"
  | "Wait"
  | "Wait2"
  | "WaitItem"
  | "WalkFast"
  | "WalkMiddle"
  | "WalkSlow"
  | "WallDamage";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}
type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<
    JSX.IntrinsicElements["skinnedMesh"] | JSX.IntrinsicElements["bone"]
  >
>;

export function Sheik(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/sheik.glb",
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Wait?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} scale={1.4} dispose={null}>
      <group name="sheik">
        <group name="Armature">
          <group name="Joint_0_Object_0">
            <skinnedMesh
              name="mesh_0"
              geometry={nodes.mesh_0.geometry}
              material={materials["Joint_0_Object_0_Material_0.001"]}
              skeleton={nodes.mesh_0.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_1">
            <skinnedMesh
              name="mesh_1"
              geometry={nodes.mesh_1.geometry}
              material={materials["Joint_0_Object_1_Material_1.001"]}
              skeleton={nodes.mesh_1.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_10">
            <skinnedMesh
              name="mesh_2"
              geometry={nodes.mesh_2.geometry}
              material={materials["Joint_0_Object_10_Material_10.001"]}
              skeleton={nodes.mesh_2.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_12">
            <skinnedMesh
              name="mesh_3"
              geometry={nodes.mesh_3.geometry}
              material={materials["Joint_0_Object_12_Material_12.001"]}
              skeleton={nodes.mesh_3.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_14">
            <skinnedMesh
              name="mesh_4"
              geometry={nodes.mesh_4.geometry}
              material={materials["Joint_0_Object_14_Material_14.001"]}
              skeleton={nodes.mesh_4.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_15">
            <skinnedMesh
              name="mesh_5"
              geometry={nodes.mesh_5.geometry}
              material={materials["Joint_0_Object_15_Material_15.001"]}
              skeleton={nodes.mesh_5.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_16">
            <skinnedMesh
              name="mesh_6"
              geometry={nodes.mesh_6.geometry}
              material={materials["Joint_0_Object_16_Material_16.001"]}
              skeleton={nodes.mesh_6.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_18">
            <skinnedMesh
              name="mesh_7"
              geometry={nodes.mesh_7.geometry}
              material={materials["Joint_0_Object_18_Material_18.001"]}
              skeleton={nodes.mesh_7.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_19">
            <skinnedMesh
              name="mesh_8"
              geometry={nodes.mesh_8.geometry}
              material={materials["Joint_0_Object_19_Material_19.001"]}
              skeleton={nodes.mesh_8.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_2">
            <skinnedMesh
              name="mesh_9"
              geometry={nodes.mesh_9.geometry}
              material={materials["Joint_0_Object_2_Material_2.001"]}
              skeleton={nodes.mesh_9.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_20">
            <skinnedMesh
              name="mesh_10"
              geometry={nodes.mesh_10.geometry}
              material={materials["Joint_0_Object_20_Material_20.001"]}
              skeleton={nodes.mesh_10.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_25">
            <skinnedMesh
              name="mesh_11"
              geometry={nodes.mesh_11.geometry}
              material={materials["Joint_0_Object_25_Material_25.001"]}
              skeleton={nodes.mesh_11.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_26">
            <skinnedMesh
              name="mesh_12"
              geometry={nodes.mesh_12.geometry}
              material={materials["Joint_0_Object_26_Material_26.001"]}
              skeleton={nodes.mesh_12.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_27">
            <skinnedMesh
              name="mesh_13"
              geometry={nodes.mesh_13.geometry}
              material={materials["Joint_0_Object_27_Material_27.001"]}
              skeleton={nodes.mesh_13.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_28">
            <skinnedMesh
              name="mesh_14"
              geometry={nodes.mesh_14.geometry}
              material={materials["Joint_0_Object_28_Material_28.001"]}
              skeleton={nodes.mesh_14.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_29">
            <skinnedMesh
              name="mesh_15"
              geometry={nodes.mesh_15.geometry}
              material={materials["Joint_0_Object_29_Material_29.001"]}
              skeleton={nodes.mesh_15.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_3">
            <skinnedMesh
              name="mesh_16"
              geometry={nodes.mesh_16.geometry}
              material={materials["Joint_0_Object_3_Material_3.001"]}
              skeleton={nodes.mesh_16.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_30">
            <skinnedMesh
              name="mesh_17"
              geometry={nodes.mesh_17.geometry}
              material={materials["Joint_0_Object_30_Material_30.001"]}
              skeleton={nodes.mesh_17.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_36">
            <skinnedMesh
              name="mesh_18"
              geometry={nodes.mesh_18.geometry}
              material={materials["Joint_0_Object_36_Material_36.001"]}
              skeleton={nodes.mesh_18.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_37">
            <skinnedMesh
              name="mesh_19"
              geometry={nodes.mesh_19.geometry}
              material={materials["Joint_0_Object_37_Material_37.001"]}
              skeleton={nodes.mesh_19.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_38">
            <skinnedMesh
              name="mesh_20"
              geometry={nodes.mesh_20.geometry}
              material={materials["Joint_0_Object_38_Material_38.001"]}
              skeleton={nodes.mesh_20.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_5">
            <skinnedMesh
              name="mesh_21"
              geometry={nodes.mesh_21.geometry}
              material={materials["Joint_0_Object_5_Material_5.001"]}
              skeleton={nodes.mesh_21.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <group name="Joint_0_Object_7">
            <skinnedMesh
              name="mesh_22"
              geometry={nodes.mesh_22.geometry}
              material={materials["Joint_0_Object_7_Material_7.001"]}
              skeleton={nodes.mesh_22.skeleton}
              position={[-7.602, -0.024, -1.16]}
              scale={0.001}
            />
          </group>
          <primitive object={nodes.JOBJ_0} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/sheik.glb");
